// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Capabilities {
    "platform": string;
    "sourceEnumeration": Capability;
    "screenRecording": Capability;
    "windowRecording": Capability;
    "applicationRecording": Capability;
    "systemAudio": Capability;
    "microphone": Capability;
    "microphoneEnhancement": Capability;
    "cameraSidecar": Capability;
    "pipExport": Capability;
    "packageRecovery": Capability;
}

export interface Capability {
    "id": string;
    "label": string;
    "status": Status;
    "backend": string;
    "permission": Permission;
    "reason"?: string;
}

export enum Permission {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PermissionNotRequired = "not-required",
    PermissionUnknown = "unknown",
    PermissionScreenRecording = "screen-recording",
    PermissionMicrophone = "microphone",
    PermissionCamera = "camera",
};

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusAvailable = "available",
    StatusQueued = "queued",
    StatusBlocked = "blocked",
    StatusUnsupported = "unsupported",
};
