// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Config {
    "preset": Preset;
    "shape": Shape;
    "mirror": boolean;
    "position": Position;
    "scale": number;
    "edgeFeather": number;
}

export interface Placement {
    "visible": boolean;
    "rect": Rect;
    "shape": Shape;
    "mirror": boolean;
    "edgeFeather": number;
}

export interface Position {
    "x": number;
    "y": number;
}

export enum Preset {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PresetOff = "off",
    PresetBottomRight = "bottom-right",
    PresetBottomLeft = "bottom-left",
    PresetFree = "free",
    DefaultPreset = "bottom-right",
};

export interface Rect {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "visible": boolean;
}

export enum Shape {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ShapeCircle = "circle",
    ShapeSquare = "square",
    DefaultShape = "circle",
};
