// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Locale,
    ShortcutAction,
    Theme
} from "./models.js";

export type {
    AudioSettings,
    CameraSettings,
    OCRSettings,
    OCRTranslationSettings,
    RecordingSettings,
    Settings,
    ShortcutSettings,
    SourceSettings,
    StorageSettings,
    WhiteboardSettings,
    WindowSettings
} from "./models.js";
