// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pip$0 from "../pip/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recordingprofile$0 from "../recordingprofile/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

export interface AudioSettings {
    "system": boolean;
    "systemDeviceId"?: string;
    "microphone": boolean;
    "microphoneDeviceId"?: string;
    "noiseSuppression": boolean;
    "microphoneGain": number;
}

export interface CameraSettings {
    "enabled": boolean;
    "deviceId"?: string;
    "pipPreset": string;
    "pip": pip$0.Config;
}

export enum Locale {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LocaleZhCN = "zh-CN",
    LocaleEN = "en",
};

export type RecordingSettings = recordingprofile$0.Profile;

export interface Settings {
    "schemaVersion": number;
    "locale": Locale;
    "source": SourceSettings;
    "storage": StorageSettings;
    "recording": RecordingSettings;
    "audio": AudioSettings;
    "camera": CameraSettings;
    "whiteboard": WhiteboardSettings;
    "shortcuts": ShortcutSettings;
    "window": WindowSettings;
    "updatedAt": time$0.Time;
}

export enum ShortcutAction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ShortcutActionToggleRecording = "toggleRecording",
    ShortcutActionTogglePause = "togglePause",
    ShortcutActionToggleCamera = "toggleCamera",
    ShortcutActionOpenWhiteboard = "openWhiteboard",
    ShortcutActionOpenScreenshot = "openScreenshot",
};

export interface ShortcutSettings {
    "toggleRecording": string;
    "togglePause": string;
    "toggleCamera": string;
    "openWhiteboard": string;
    "openScreenshot": string;
}

export interface SourceSettings {
    "lastSourceId"?: string;
    "lastSourceType": string;
}

export interface StorageSettings {
    "dataRootDir"?: string;
}

export enum Theme {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemeNightTeal = "night-teal",
    ThemeMountainGreen = "mountain-green",
    ThemeSkyBlue = "sky-blue",
    ThemeSunsetYellow = "sunset-yellow",
    ThemeInkPurple = "ink-purple",
    ThemeSageGray = "sage-gray",
};

export interface WhiteboardSettings {
    "enabled": boolean;
    "lastMode": string;
    "lastTool": string;
    "lastStrokeColor": string;
    "lastStrokeWidth": string;
    "lastOpacity": number;
    "capturePolicy": string;
}

export interface WindowSettings {
    "minimizeToTray": boolean;
    "theme": Theme;
    "startAtLogin": boolean;
}
