// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

export interface Block {
    "id": string;
    "text": string;
    "confidence": number;
    "box": Point[] | null;
    "lineIndex": number;
    "languageHint"?: string;
}

export interface JobSnapshot {
    "jobId": string;
    "status": string;
    "cacheKey"?: string;
    "request": RecognizeRequest;
    "merged": boolean;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
}

export interface ModelDownloadEvent {
    "snapshot": ModelDownloadSnapshot;
}

export interface ModelDownloadSnapshot {
    "id": string;
    "modelId": string;
    "status": string;
    "downloadedBytes": number;
    "totalBytes": number;
    "percent": number;
    "error"?: string;
    "model"?: ModelInfo | null;
    "startedAt": time$0.Time;
    "updatedAt": time$0.Time;
}

export interface ModelInfo {
    "id": string;
    "name": string;
    "channel": string;
    "engine": string;
    "language": string[] | null;
    "version"?: string;
    "sourceUrl"?: string;
    "license"?: string;
    "downloadAvailable"?: boolean;
    "downloadBytes"?: number;
    "installed": boolean;
    "verified": boolean;
    "active": boolean;
    "modelDir"?: string;
    "smokeImage"?: string;
    "smokeExpected"?: string;
    "smokeAssetReady"?: boolean;
    "smokeError"?: string;
    "missingFiles"?: string[] | null;
    "verificationError"?: string;
}

export interface Point {
    "x": number;
    "y": number;
}

export interface RecognizeRequest {
    "imagePath": string;
    "sourceKind": SourceKind;
    "sourceId": string;
    "language": string;
    "modelId"?: string;
    "force": boolean;
    "priority": string;
}

export interface Result {
    "id": string;
    "sourceKind": SourceKind;
    "sourceId": string;
    "imagePath": string;
    "imageSha256": string;
    "modelId": string;
    "language": string;
    "width": number;
    "height": number;
    "blocks": Block[] | null;
    "plainText": string;
    "createdAt": time$0.Time;
    "durationMs": number;
}

export enum SourceKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SourceRegionScreenshot = "region-screenshot",
    SourceFullScreenshot = "full-screenshot",
    SourceWindowScreenshot = "window-screenshot",
    SourceFocusedWindowScreenshot = "focused-window-screenshot",
    SourceScrollingScreenshot = "scrolling-screenshot",
    SourcePinnedScreenshot = "pinned-screenshot",
    SourceWhiteboard = "whiteboard",
    SourceWhiteboardSelection = "whiteboard-selection",
    SourceImage = "image",
};

export interface Status {
    "status": string;
    "activeModelId"?: string;
    "models": ModelInfo[] | null;
    "workerPath"?: string;
    "runtimeDir"?: string;
    "workerCapabilities"?: WorkerCapabilities | null;
    "message"?: string;
}

export interface TranslateRequest {
    "ocrResultId": string;
    "blockIds"?: string[] | null;
    "provider": string;
    "sourceLanguage": string;
    "targetLanguage": string;
    "baseUrl"?: string;
    "apiKey"?: string;
    "model"?: string;
    "force": boolean;
}

export interface TranslationBlock {
    "blockId": string;
    "source": string;
    "translated": string;
}

export interface TranslationResult {
    "ocrResultId": string;
    "provider": string;
    "sourceLanguage": string;
    "targetLanguage": string;
    "model"?: string;
    "promptVersion"?: string;
    "blocks": TranslationBlock[] | null;
    "createdAt": time$0.Time;
}

export interface WhiteboardRequest {
    "imagePath": string;
    "elementId"?: string;
    "sceneId"?: string;
    "language"?: string;
    "force": boolean;
    "priority"?: string;
}

export interface WorkerCapabilities {
    "schemaVersion": number;
    "name": string;
    "version": string;
    "protocolVersion": string;
    "engine": string;
    "modelFormats": string[] | null;
    "supportsRecognize": boolean;
    "runtimeDir"?: string;
    "runtimeLibrary"?: string;
    "runtimeAvailable": boolean;
    "runtimeVersion"?: string;
    "runtimeApiVersion"?: number;
    "runtimeError"?: string;
    "message"?: string;
}
