// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Result {
    "outputPath": string;
    "bytes": number;
    "screenInputPath": string;
    "webcamInputPath"?: string;
    "pipVisible": boolean;
    "ffmpegPath": string;
    "outputVerified": boolean;
}
