// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as devices$0 from "../devices/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recordingprofile$0 from "../recordingprofile/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

export interface AudioOnlyRequest {
    "recording": recordingprofile$0.Profile;
    "audio": AudioRequest;
}

export interface AudioRequest {
    "system": boolean;
    "systemDeviceId"?: string;
    "microphone": boolean;
    "microphoneDeviceId"?: string;
    "noiseSuppression": boolean;
    "microphoneGain": number;
}

export interface CameraRequest {
    "enabled": boolean;
    "deviceId"?: string;
    "deviceNativeId"?: string;
    "pipPreset": string;
}

export type CaptureSourceType = devices$0.CaptureSourceType;

export interface Session {
    "id": string;
    "packageDir": string;
    "manifest": string;
    "backend": string;
    "recordingMode": string;
    "status": State;
    "startedAt": time$0.Time;
    "completedAt"?: time$0.Time;
}

export interface SourceGeometry {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "displayIndex"?: number;
    "nativeId"?: string;
}

export interface StartRequest {
    "sourceId": string;
    "sourceType": CaptureSourceType;
    "sourceName"?: string;
    "sourceGeometry"?: SourceGeometry | null;
    "recording": recordingprofile$0.Profile;
    "audio": AudioRequest;
    "camera": CameraRequest;
}

export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateIdle = "idle",
    StatePreparing = "preparing",
    StateRecording = "recording",
    StatePaused = "paused",
    StateStopping = "stopping",
    StateReady = "ready",
    StateFailed = "failed",
};

export interface StatusEvent {
    "status": State;
    "sessionId"?: string;
    "packageDir"?: string;
    "manifest"?: string;
    "backend"?: string;
    "message"?: string;
}
