// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../lemon-casino/RecordingFreedom/app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as recording$0 from "../../../../lemon-casino/RecordingFreedom/app/internal/recording/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as settings$0 from "../../../../lemon-casino/RecordingFreedom/app/internal/settings/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "audio.level": main$0.AudioLevelEvent;
            "audio.state": main$0.AudioState;
            "capture.region.selected": main$0.RegionSelectionResult;
            "floating.panel.changed": main$0.FloatingPanelState;
            "floating.select.changed": main$0.FloatingSelectState;
            "floating.select.chosen": main$0.FloatingSelectChosenEvent;
            "recording.status": recording$0.StatusEvent;
            "screenshot.captured": main$0.ScreenshotCapturedEvent;
            "screenshot.pin": main$0.ScreenshotPinEvent;
            "screenshot.whiteboard": main$0.ScreenshotWhiteboardContext;
            "settings.changed": settings$0.Settings;
            "shortcut.triggered": main$0.ShortcutTriggeredEvent;
            "source.state.changed": main$0.SourceControlState;
            "whiteboard.visibility": main$0.WhiteboardVisibilityEvent;
        }
    }
}
