// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as recording$0 from "../../../../lemon-casino/RecordingFreedom/app/internal/recording/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "recording.status": recording$0.StatusEvent;
        }
    }
}
