// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as RecordingFreedomService from "./recordingfreedomservice.js";
export {
    RecordingFreedomService
};

export type {
    BootstrapState,
    RegionRect,
    RegionSelectionRequest,
    RegionSelectionResult,
    RegionSelectionSession,
    ScreenIndicatorRequest,
    ScreenIndicatorResult
} from "./models.js";
