// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as RecordingFreedomService from "./recordingfreedomservice.js";
export {
    RecordingFreedomService
};

export type {
    AudioLevelEvent,
    AudioState,
    AudioStatePatchRequest,
    BootstrapState,
    CapsuleWindowHitRegion,
    CapsuleWindowHitRegionsRequest,
    ClientLogEvent,
    ExportRecordingRequest,
    ExportRecordingResult,
    PIPCamera,
    PIPOverlayRequest,
    PIPOverlayState,
    PIPPreviewImageRequest,
    PIPPreviewImageResult,
    RegionRect,
    RegionSelectionRequest,
    RegionSelectionResult,
    RegionSelectionSession,
    ScreenIndicatorRequest,
    ScreenIndicatorResult
} from "./models.js";
