// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appdata$0 from "./internal/appdata/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capture$0 from "./internal/capture/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as devices$0 from "./internal/devices/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recording$0 from "./internal/recording/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recpackage$0 from "./internal/recpackage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "./internal/settings/models.js";

export interface AudioLevelEvent {
    "deviceId": string;
    "level": number;
    "rms": number;
    "peak": number;
    "active": boolean;
    "error"?: string;
}

export interface BootstrapState {
    "appData": appdata$0.Info;
    "storage": appdata$0.StorageStatus;
    "state": recording$0.State;
    "backend": string;
    "sources": devices$0.CaptureSource[] | null;
    "media": devices$0.MediaInventory;
    "recoveries": recpackage$0.RecoverySummary[] | null;
    "settings": settings$0.Settings;
    "capabilities": capture$0.Capabilities;
}

export interface RegionRect {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
}

export interface RegionSelectionRequest {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
}

export interface RegionSelectionResult {
    "sessionId"?: string;
    "source"?: devices$0.CaptureSource;
    "geometry"?: RegionRect;
    "cancelled": boolean;
    "error"?: string;
}

export interface RegionSelectionSession {
    "id": string;
    "bounds": RegionRect;
    "minimumWidth": number;
    "minimumHeight": number;
    "displayCount": number;
}

export interface ScreenIndicatorRequest {
    "sourceId": string;
}

export interface ScreenIndicatorResult {
    "sourceId": string;
    "displayIndex": number;
    "label": string;
    "sourceBounds": RegionRect;
    "windowBounds": RegionRect;
}
