// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appdata$0 from "./internal/appdata/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capture$0 from "./internal/capture/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as devices$0 from "./internal/devices/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as exporter$0 from "./internal/exporter/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as exportplan$0 from "./internal/exportplan/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ocr$0 from "./internal/ocr/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pip$0 from "./internal/pip/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recording$0 from "./internal/recording/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recpackage$0 from "./internal/recpackage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "./internal/settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

export interface AnnotationCaptureRequest {
    "sceneJson": string;
    "snapshotDataUrl": string;
    "eventsJsonl"?: string;
}

export interface AnnotationCaptureResult {
    "packageDir": string;
    "scenePath": string;
    "eventsPath": string;
    "snapshotPath": string;
    "timelineSnapshotPath"?: string;
    "bytes": number;
}

export interface AnnotationOverlayState {
    "mode"?: string;
    "packageDir"?: string;
    "manifestPath"?: string;
    "windowBounds": RegionRect;
    "canvasBounds": RegionRect;
    "toolbarBounds"?: RegionRect;
    "toolbarPlacement"?: string;
    "target": recpackage$0.ManifestAnnotationTarget;
    "captureExcluded": boolean;
}

export interface AnnotationPreviewImageRequest {
    "packageDir": string;
    "snapshotPath": string;
}

export interface AnnotationPreviewImageResult {
    "available": boolean;
    "dataUrl"?: string;
    "relativePath"?: string;
    "bytes"?: number;
}

export interface AnnotationRenderJob {
    "id": string;
    "packageDir": string;
    "scenePath": string;
    "relativeScenePath": string;
    "outputPath": string;
    "relativeOutputPath": string;
    "sceneJson": string;
    "canvasWidth": number;
    "canvasHeight": number;
    "index": number;
    "startOffsetMs"?: number;
    "endOffsetMs"?: number;
}

export interface AnnotationRenderJobClaim {
    "available": boolean;
    "job"?: AnnotationRenderJob | null;
}

export interface AnnotationRenderJobResult {
    "id": string;
    "dataUrl"?: string;
    "error"?: string;
}

export interface AudioLevelEvent {
    "deviceId": string;
    "level": number;
    "rms": number;
    "peak": number;
    "active": boolean;
    "error"?: string;
}

export interface AudioState {
    "system": boolean;
    "systemDeviceId"?: string;
    "microphone": boolean;
    "microphoneDeviceId"?: string;
    "noiseSuppression": boolean;
    "microphoneGain": number;
}

export interface AudioStatePatchRequest {
    "system"?: boolean | null;
    "systemDeviceId"?: string | null;
    "microphone"?: boolean | null;
    "microphoneDeviceId"?: string | null;
    "noiseSuppression"?: boolean | null;
    "microphoneGain"?: number | null;
    "clearSystemDevice"?: boolean;
    "clearMicrophoneDevice"?: boolean;
}

export interface BootstrapState {
    "appData": appdata$0.Info;
    "storage": appdata$0.StorageStatus;
    "state": recording$0.State;
    "backend": string;
    "sources": devices$0.CaptureSource[] | null;
    "media": devices$0.MediaInventory;
    "recoveries": recpackage$0.RecoverySummary[] | null;
    "settings": settings$0.Settings;
    "capabilities": capture$0.Capabilities;
}

export interface CameraStatePatchRequest {
    "enabled"?: boolean | null;
    "deviceId"?: string | null;
    "pipPreset"?: string | null;
    "pip"?: pip$0.Config | null;
}

export interface CapsuleWindowHitRegion {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "kind"?: string;
    "radius"?: number;
}

export interface CapsuleWindowHitRegionsRequest {
    "enabled": boolean;
    "force"?: boolean;
    "viewportWidth": number;
    "viewportHeight": number;
    "devicePixelRatio": number;
    "regions": CapsuleWindowHitRegion[] | null;
}

export interface ClientLogEvent {
    "component": string;
    "event": string;
    "message"?: string;
    "fields"?: { [_ in string]?: string } | null;
}

export interface ExportRecordingPlanResult {
    "plan": exportplan$0.Plan;
}

export interface ExportRecordingRequest {
    "packageDir": string;
    "outputPath"?: string;
    "canvasWidth"?: number;
    "canvasHeight"?: number;
    "includeAnnotations"?: boolean | null;
}

export interface ExportRecordingResult {
    "plan": exportplan$0.Plan;
    "export": exporter$0.Result;
}

export enum FloatingPanelKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FloatingPanelSource = "source",
    FloatingPanelAudio = "audio",
    FloatingPanelCamera = "camera",
    FloatingPanelBoard = "board",
    FloatingPanelLanguage = "language",
    FloatingPanelSettings = "settings",
    FloatingPanelClose = "close",
    FloatingPanelOCRResult = "ocr-result",
};

export interface FloatingPanelRequest {
    "kind": FloatingPanelKind;
    "anchor": FloatingRect;
    "bounds": FloatingRect;
    "dockSide"?: string;
    "width": number;
    "height": number;
    "minWidth"?: number;
    "maxHeight"?: number;
    "token": number;
    "screenId"?: string;
    "direction"?: string;
    "contextId"?: string;
}

export interface FloatingPanelState {
    "visible": boolean;
    "kind"?: FloatingPanelKind;
    "anchor": FloatingRect;
    "bounds": FloatingRect;
    "dockSide"?: string;
    "token": number;
    "screenId"?: string;
    "direction"?: string;
    "contextId"?: string;
    "updatedAt": time$0.Time;
}

export interface FloatingRect {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
}

export interface FloatingSelectChosenEvent {
    "id": string;
    "value": string;
    "token": number;
    "panelToken"?: number;
}

export interface FloatingSelectOption {
    "value": string;
    "label": string;
    "disabled"?: boolean;
    "swatch"?: string;
}

export interface FloatingSelectRequest {
    "id": string;
    "anchor": FloatingRect;
    "bounds": FloatingRect;
    "value": string;
    "options": FloatingSelectOption[] | null;
    "token": number;
    "panelToken"?: number;
    "width"?: number;
    "maxHeight"?: number;
    "screenId"?: string;
    "direction"?: string;
}

export interface FloatingSelectState {
    "visible": boolean;
    "id"?: string;
    "anchor": FloatingRect;
    "bounds": FloatingRect;
    "value"?: string;
    "options"?: FloatingSelectOption[] | null;
    "token": number;
    "panelToken"?: number;
    "screenId"?: string;
    "direction"?: string;
    "updatedAt": time$0.Time;
}

export interface OCRTranslationPreferencesPatchRequest {
    "provider"?: string | null;
    "baseUrl"?: string | null;
    "apiKey"?: string | null;
    "model"?: string | null;
    "sourceLanguage"?: string | null;
    "targetLanguage"?: string | null;
    "privacyConfirmed"?: boolean | null;
    "privacyConfirmedAt"?: string | null;
}

export interface OcrJobEvent {
    "event"?: string;
    "jobId": string;
    "sourceKind": ocr$0.SourceKind;
    "sourceId": string;
    "status": string;
    "cacheKey"?: string;
    "merged"?: boolean;
    "error"?: string;
    "result"?: ocr$0.Result | null;
}

export interface OcrModelEvent {
    "modelId": string;
    "status": string;
    "error"?: string;
    "model"?: ocr$0.ModelInfo | null;
}

export interface PIPCamera {
    "deviceId"?: string;
    "nativeId"?: string;
    "name"?: string;
}

export interface PIPOverlayRequest {
    "config": pip$0.Config;
    "mode"?: string;
    "cameraName"?: string;
    "camera"?: PIPCamera;
    "previewImagePath"?: string;
    "clientOperationId"?: number;
}

export interface PIPOverlayState {
    "config": pip$0.Config;
    "placement": pip$0.Placement;
    "overlayBounds": RegionRect;
    "windowBounds": RegionRect;
    "contentBounds": RegionRect;
    "mode": string;
    "cameraName"?: string;
    "camera"?: PIPCamera;
    "previewImagePath"?: string;
    "captureExcluded": boolean;
    "clientOperationId"?: number;
}

export interface PIPPreviewImageRequest {
    "path": string;
    "knownModifiedUnixNano"?: number;
}

export interface PIPPreviewImageResult {
    "available": boolean;
    "dataUrl"?: string;
    "modifiedUnixNano"?: number;
}

export interface RegionAssistRequest {
    "sessionId"?: string;
    "purpose"?: string;
    "pointerX"?: number;
    "pointerY"?: number;
    "selection"?: RegionRect | null;
    "candidateLevel"?: number;
}

export interface RegionAssistResult {
    "candidates": RegionSmartCandidate[] | null;
    "best"?: RegionSmartCandidate | null;
    "source"?: string;
}

export interface RegionDisplayBounds {
    "id"?: string;
    "bounds": RegionRect;
    "captureBounds": RegionRect;
    "scaleFactor"?: number;
}

export interface RegionFrameState {
    "bounds": RegionRect;
    "overlayBounds"?: RegionRect;
    "mode": string;
    "purpose"?: string;
}

export interface RegionPoint {
    "x": number;
    "y": number;
}

export interface RegionRect {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
}

export interface RegionSelectionRequest {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
}

export interface RegionSelectionResult {
    "sessionId"?: string;
    "source"?: devices$0.CaptureSource;
    "geometry"?: RegionRect;
    "cancelled": boolean;
    "error"?: string;
}

export interface RegionSelectionSession {
    "id": string;
    "bounds": RegionRect;
    "captureBounds"?: RegionRect | null;
    "displayBounds"?: RegionDisplayBounds[] | null;
    "minimumWidth": number;
    "minimumHeight": number;
    "displayCount": number;
    "purpose"?: string;
    "candidates"?: RegionSmartCandidate[] | null;
    "initialPointer"?: RegionPoint | null;
}

export interface RegionSmartCandidate {
    "id": string;
    "kind": string;
    "label"?: string;
    "bounds": RegionRect;
    "sourceId"?: string;
    "score"?: number;
}

export interface ScreenIndicatorRequest {
    "sourceId": string;
}

export interface ScreenIndicatorResult {
    "sourceId": string;
    "displayIndex": number;
    "label": string;
    "sourceBounds": RegionRect;
    "windowBounds": RegionRect;
}

export interface ScreenshotCaptureRequest {
    "mode"?: string;
    "region"?: RegionRect | null;
}

export interface ScreenshotCaptureResult {
    "item": ScreenshotItem;
}

export interface ScreenshotCapturedEvent {
    "item": ScreenshotItem;
}

export interface ScreenshotHistoryResult {
    "items": ScreenshotItem[] | null;
}

export interface ScreenshotImageRequest {
    "id"?: string;
    "path"?: string;
    "thumbnail"?: boolean;
}

export interface ScreenshotImageResult {
    "available": boolean;
    "dataUrl"?: string;
    "path"?: string;
    "bytes"?: number;
}

export interface ScreenshotItem {
    "id": string;
    "path": string;
    "thumbnailPath"?: string;
    "createdAt": string;
    "width": number;
    "height": number;
    "mode": string;
    "region"?: RegionRect | null;
    "pinned": boolean;
    "fixed": boolean;
    "ocrStatus": string;
    "ocrResultId"?: string;
    "ocrModelId"?: string;
    "ocrLanguage"?: string;
    "ocrUpdatedAt"?: string;
    "ocrError"?: string;
}

export interface ScreenshotItemPatchRequest {
    "id": string;
    "pinned"?: boolean | null;
    "fixed"?: boolean | null;
}

export interface ScreenshotPinEvent {
    "visible": boolean;
    "item"?: ScreenshotItem;
    "dataUrl"?: string;
    "fixed": boolean;
    "pins"?: ScreenshotPinnedItem[] | null;
}

export interface ScreenshotPinState {
    "visible": boolean;
    "item"?: ScreenshotItem;
    "dataUrl"?: string;
    "fixed": boolean;
    "pins"?: ScreenshotPinnedItem[] | null;
}

export interface ScreenshotPinnedItem {
    "item": ScreenshotItem;
    "dataUrl"?: string;
    "fixed": boolean;
}

export interface ScreenshotWhiteboardContext {
    "available": boolean;
    "item"?: ScreenshotItem;
    "dataUrl"?: string;
}

export interface SettingsPreferencesPatchRequest {
    "theme"?: settings$0.Theme | null;
    "recordingQuality"?: string | null;
    "recordingFps"?: number | null;
    "captureCursor"?: boolean | null;
    "countdownSeconds"?: number | null;
    "startAtLogin"?: boolean | null;
    "autoOcr"?: boolean | null;
    "ocrTranslation"?: OCRTranslationPreferencesPatchRequest | null;
}

export interface ShortcutSettingsPatchRequest {
    "toggleRecording"?: string | null;
    "togglePause"?: string | null;
    "toggleCamera"?: string | null;
    "openWhiteboard"?: string | null;
    "openScreenshot"?: string | null;
    "pasteImage"?: string | null;
}

export interface ShortcutTriggeredEvent {
    "action": settings$0.ShortcutAction;
    "accelerator": string;
}

export interface SourceControlState {
    "recordingMode": string;
    "sourceId"?: string;
    "sourceType"?: string;
    "sourceGeometry"?: SourceGeometry | null;
    "updatedAt": time$0.Time;
}

export interface SourceGeometry {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "displayIndex"?: number;
    "nativeId"?: string;
}

export interface SourceStatePatchRequest {
    "recordingMode"?: string;
    "sourceId"?: string;
    "sourceType"?: string;
    "sourceGeometry"?: SourceGeometry | null;
    "clearGeometry"?: boolean;
}

export interface WhiteboardExportRequest {
    "format": string;
    "dataUrl"?: string;
    "payload"?: string;
}

export interface WhiteboardExportResult {
    "format": string;
    "outputPath": string;
    "bytes": number;
}

export interface WhiteboardSceneRequest {
    "sceneJson": string;
}

export interface WhiteboardSceneResult {
    "available": boolean;
    "scenePath": string;
    "sceneJson"?: string;
    "bytes": number;
    "updatedAt"?: string;
    "contentType"?: string;
}

export interface WhiteboardSettingsPatchRequest {
    "enabled"?: boolean | null;
    "lastMode"?: string | null;
    "lastTool"?: string | null;
    "lastStrokeColor"?: string | null;
    "lastStrokeWidth"?: string | null;
    "lastOpacity"?: number | null;
    "capturePolicy"?: string | null;
}

export interface WhiteboardSnapshotRequest {
    "sceneJson": string;
    "snapshotDataUrl": string;
}

export interface WhiteboardSnapshotResult {
    "scene": WhiteboardSceneResult;
    "item": ScreenshotItem;
}

export interface WhiteboardVisibilityEvent {
    "visible": boolean;
    "mode": string;
}
