// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appdata$0 from "./internal/appdata/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capture$0 from "./internal/capture/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as devices$0 from "./internal/devices/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as exporter$0 from "./internal/exporter/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as exportplan$0 from "./internal/exportplan/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pip$0 from "./internal/pip/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recording$0 from "./internal/recording/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recpackage$0 from "./internal/recpackage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "./internal/settings/models.js";

export interface AnnotationCaptureRequest {
    "sceneJson": string;
    "snapshotDataUrl": string;
    "eventsJsonl"?: string;
}

export interface AnnotationCaptureResult {
    "packageDir": string;
    "scenePath": string;
    "eventsPath": string;
    "snapshotPath": string;
    "timelineSnapshotPath"?: string;
    "bytes": number;
}

export interface AnnotationOverlayState {
    "packageDir"?: string;
    "manifestPath"?: string;
    "windowBounds": RegionRect;
    "canvasBounds": RegionRect;
    "target": recpackage$0.ManifestAnnotationTarget;
    "captureExcluded": boolean;
}

export interface AnnotationPreviewImageRequest {
    "packageDir": string;
    "snapshotPath": string;
}

export interface AnnotationPreviewImageResult {
    "available": boolean;
    "dataUrl"?: string;
    "relativePath"?: string;
    "bytes"?: number;
}

export interface AnnotationRenderJob {
    "id": string;
    "packageDir": string;
    "scenePath": string;
    "relativeScenePath": string;
    "outputPath": string;
    "relativeOutputPath": string;
    "sceneJson": string;
    "canvasWidth": number;
    "canvasHeight": number;
    "index": number;
    "startOffsetMs"?: number;
    "endOffsetMs"?: number;
}

export interface AnnotationRenderJobClaim {
    "available": boolean;
    "job"?: AnnotationRenderJob | null;
}

export interface AnnotationRenderJobResult {
    "id": string;
    "dataUrl"?: string;
    "error"?: string;
}

export interface AudioLevelEvent {
    "deviceId": string;
    "level": number;
    "rms": number;
    "peak": number;
    "active": boolean;
    "error"?: string;
}

export interface AudioState {
    "system": boolean;
    "systemDeviceId"?: string;
    "microphone": boolean;
    "microphoneDeviceId"?: string;
    "noiseSuppression": boolean;
    "microphoneGain": number;
}

export interface AudioStatePatchRequest {
    "system"?: boolean | null;
    "systemDeviceId"?: string | null;
    "microphone"?: boolean | null;
    "microphoneDeviceId"?: string | null;
    "noiseSuppression"?: boolean | null;
    "microphoneGain"?: number | null;
    "clearSystemDevice"?: boolean;
    "clearMicrophoneDevice"?: boolean;
}

export interface BootstrapState {
    "appData": appdata$0.Info;
    "storage": appdata$0.StorageStatus;
    "state": recording$0.State;
    "backend": string;
    "sources": devices$0.CaptureSource[] | null;
    "media": devices$0.MediaInventory;
    "recoveries": recpackage$0.RecoverySummary[] | null;
    "settings": settings$0.Settings;
    "capabilities": capture$0.Capabilities;
}

export interface CapsuleWindowHitRegion {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "kind"?: string;
    "radius"?: number;
}

export interface CapsuleWindowHitRegionsRequest {
    "enabled": boolean;
    "force"?: boolean;
    "viewportWidth": number;
    "viewportHeight": number;
    "devicePixelRatio": number;
    "regions": CapsuleWindowHitRegion[] | null;
}

export interface ClientLogEvent {
    "component": string;
    "event": string;
    "message"?: string;
    "fields"?: { [_ in string]?: string } | null;
}

export interface ExportRecordingPlanResult {
    "plan": exportplan$0.Plan;
}

export interface ExportRecordingRequest {
    "packageDir": string;
    "outputPath"?: string;
    "canvasWidth"?: number;
    "canvasHeight"?: number;
    "includeAnnotations"?: boolean | null;
}

export interface ExportRecordingResult {
    "plan": exportplan$0.Plan;
    "export": exporter$0.Result;
}

export interface PIPCamera {
    "deviceId"?: string;
    "nativeId"?: string;
    "name"?: string;
}

export interface PIPOverlayRequest {
    "config": pip$0.Config;
    "mode"?: string;
    "cameraName"?: string;
    "camera"?: PIPCamera;
    "previewImagePath"?: string;
}

export interface PIPOverlayState {
    "config": pip$0.Config;
    "placement": pip$0.Placement;
    "overlayBounds": RegionRect;
    "windowBounds": RegionRect;
    "contentBounds": RegionRect;
    "mode": string;
    "cameraName"?: string;
    "camera"?: PIPCamera;
    "previewImagePath"?: string;
    "captureExcluded": boolean;
}

export interface PIPPreviewImageRequest {
    "path": string;
    "knownModifiedUnixNano"?: number;
}

export interface PIPPreviewImageResult {
    "available": boolean;
    "dataUrl"?: string;
    "modifiedUnixNano"?: number;
}

export interface RegionRect {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
}

export interface RegionSelectionRequest {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
}

export interface RegionSelectionResult {
    "sessionId"?: string;
    "source"?: devices$0.CaptureSource;
    "geometry"?: RegionRect;
    "cancelled": boolean;
    "error"?: string;
}

export interface RegionSelectionSession {
    "id": string;
    "bounds": RegionRect;
    "minimumWidth": number;
    "minimumHeight": number;
    "displayCount": number;
}

export interface ScreenIndicatorRequest {
    "sourceId": string;
}

export interface ScreenIndicatorResult {
    "sourceId": string;
    "displayIndex": number;
    "label": string;
    "sourceBounds": RegionRect;
    "windowBounds": RegionRect;
}

export interface SettingsPreferencesPatchRequest {
    "theme"?: settings$0.Theme | null;
    "recordingQuality"?: string | null;
    "recordingFps"?: number | null;
    "captureCursor"?: boolean | null;
    "countdownSeconds"?: number | null;
}

export interface WhiteboardExportRequest {
    "format": string;
    "dataUrl"?: string;
    "payload"?: string;
}

export interface WhiteboardExportResult {
    "format": string;
    "outputPath": string;
    "bytes": number;
}

export interface WhiteboardSceneRequest {
    "sceneJson": string;
}

export interface WhiteboardSceneResult {
    "available": boolean;
    "scenePath": string;
    "sceneJson"?: string;
    "bytes": number;
    "updatedAt"?: string;
    "contentType"?: string;
}

export interface WhiteboardSettingsPatchRequest {
    "enabled"?: boolean | null;
    "lastMode"?: string | null;
    "lastTool"?: string | null;
    "lastStrokeColor"?: string | null;
    "lastStrokeWidth"?: string | null;
    "lastOpacity"?: number | null;
    "capturePolicy"?: string | null;
}

export interface WhiteboardVisibilityEvent {
    "visible": boolean;
    "mode": string;
}
