// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appdata$0 from "./internal/appdata/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capture$0 from "./internal/capture/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as devices$0 from "./internal/devices/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as preflight$0 from "./internal/preflight/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recording$0 from "./internal/recording/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recpackage$0 from "./internal/recpackage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "./internal/settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BeginScreenshotRegionEdit(req: $models.RegionSelectionRequest): $CancellablePromise<$models.RegionFrameState> {
    return $Call.ByID(1479485771, req);
}

export function Bootstrap(): $CancellablePromise<$models.BootstrapState> {
    return $Call.ByID(3811015052);
}

export function CancelRegionSelection(): $CancellablePromise<$models.RegionSelectionResult> {
    return $Call.ByID(3597544006);
}

export function CancelSelectedRegion(): $CancellablePromise<$models.RegionSelectionResult> {
    return $Call.ByID(1279436437);
}

export function CaptureScreenshot(req: $models.ScreenshotCaptureRequest): $CancellablePromise<$models.ScreenshotCaptureResult> {
    return $Call.ByID(3383706216, req);
}

export function ClaimAnnotationRenderJob(): $CancellablePromise<$models.AnnotationRenderJobClaim> {
    return $Call.ByID(3090640534);
}

export function CompleteAnnotationRegionSelection(req: $models.RegionSelectionRequest): $CancellablePromise<$models.AnnotationOverlayState> {
    return $Call.ByID(1407637282, req);
}

export function CompleteAnnotationRenderJob(result: $models.AnnotationRenderJobResult): $CancellablePromise<void> {
    return $Call.ByID(1422662043, result);
}

export function CompleteRegionSelection(req: $models.RegionSelectionRequest): $CancellablePromise<$models.RegionSelectionResult> {
    return $Call.ByID(1962254349, req);
}

export function CompleteScreenshotRegionSelection(req: $models.RegionSelectionRequest): $CancellablePromise<$models.ScreenshotCaptureResult> {
    return $Call.ByID(167393633, req);
}

export function ConsumeScreenshotWhiteboardContext(): $CancellablePromise<$models.ScreenshotWhiteboardContext> {
    return $Call.ByID(3553890718);
}

export function DeleteScreenshotItem(id: string): $CancellablePromise<$models.ScreenshotHistoryResult> {
    return $Call.ByID(3839519758, id);
}

export function ExportRecordingPackage(req: $models.ExportRecordingRequest): $CancellablePromise<$models.ExportRecordingResult> {
    return $Call.ByID(2136941557, req);
}

export function GetCaptureCapabilities(): $CancellablePromise<capture$0.Capabilities> {
    return $Call.ByID(4009257246);
}

export function GetSettings(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1085525119);
}

export function HideAnnotationOverlay(): $CancellablePromise<void> {
    return $Call.ByID(3633794229);
}

export function HidePIPOverlay(): $CancellablePromise<void> {
    return $Call.ByID(2267008089);
}

export function HidePinnedScreenshot(): $CancellablePromise<void> {
    return $Call.ByID(371308924);
}

export function HideRegionFrame(): $CancellablePromise<void> {
    return $Call.ByID(1481407147);
}

export function HideScreenIndicator(): $CancellablePromise<void> {
    return $Call.ByID(3727544311);
}

export function HideSettingsWindow(): $CancellablePromise<void> {
    return $Call.ByID(4158023747);
}

export function HideWhiteboardWindow(): $CancellablePromise<void> {
    return $Call.ByID(3405865905);
}

export function ListMediaDevices(): $CancellablePromise<devices$0.MediaInventory> {
    return $Call.ByID(2412119741);
}

export function ListScreenshots(): $CancellablePromise<$models.ScreenshotHistoryResult> {
    return $Call.ByID(3235644791);
}

export function ListSources(): $CancellablePromise<devices$0.CaptureSource[] | null> {
    return $Call.ByID(3137910140);
}

export function LoadAnnotationCapture(): $CancellablePromise<$models.WhiteboardSceneResult> {
    return $Call.ByID(2840498151);
}

export function LoadPinnedScreenshot(): $CancellablePromise<$models.ScreenshotPinState> {
    return $Call.ByID(1332827708);
}

export function LoadWhiteboardScene(): $CancellablePromise<$models.WhiteboardSceneResult> {
    return $Call.ByID(3447890335);
}

export function LogClientEvent(event: $models.ClientLogEvent): $CancellablePromise<void> {
    return $Call.ByID(1000984385, event);
}

export function OpenRecordingPackage(packageDir: string): $CancellablePromise<recpackage$0.RecoverySummary> {
    return $Call.ByID(339423795, packageDir);
}

export function OpenScreenshot(req: $models.ScreenshotImageRequest): $CancellablePromise<$models.ScreenshotItem> {
    return $Call.ByID(3167145418, req);
}

export function OpenScreenshotDirectory(req: $models.ScreenshotImageRequest): $CancellablePromise<$models.ScreenshotItem> {
    return $Call.ByID(951793161, req);
}

export function OpenScreenshotInWhiteboard(id: string): $CancellablePromise<$models.ScreenshotWhiteboardContext> {
    return $Call.ByID(1096524846, id);
}

export function OpenVideoDirectory(): $CancellablePromise<appdata$0.Info> {
    return $Call.ByID(1462702352);
}

export function PatchAudioState(patch: $models.AudioStatePatchRequest): $CancellablePromise<$models.AudioState> {
    return $Call.ByID(680645443, patch);
}

export function PatchScreenshotItem(req: $models.ScreenshotItemPatchRequest): $CancellablePromise<$models.ScreenshotHistoryResult> {
    return $Call.ByID(4203171135, req);
}

export function PatchSettingsPreferences(patch: $models.SettingsPreferencesPatchRequest): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(2494029929, patch);
}

export function PatchShortcutSettings(patch: $models.ShortcutSettingsPatchRequest): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(173406099, patch);
}

export function PatchWhiteboardSettings(patch: $models.WhiteboardSettingsPatchRequest): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(3918109714, patch);
}

export function PauseRecording(): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(2282766307);
}

export function PreflightAudioOnlyRecording(req: recording$0.AudioOnlyRequest): $CancellablePromise<preflight$0.Summary> {
    return $Call.ByID(992673734, req);
}

export function PreflightRecording(req: recording$0.StartRequest): $CancellablePromise<preflight$0.Summary> {
    return $Call.ByID(2137129988, req);
}

export function PreviewExportRecordingPackage(req: $models.ExportRecordingRequest): $CancellablePromise<$models.ExportRecordingPlanResult> {
    return $Call.ByID(960079289, req);
}

export function ReadAnnotationPreviewImage(req: $models.AnnotationPreviewImageRequest): $CancellablePromise<$models.AnnotationPreviewImageResult> {
    return $Call.ByID(2093045446, req);
}

export function ReadPIPPreviewImage(req: $models.PIPPreviewImageRequest): $CancellablePromise<$models.PIPPreviewImageResult> {
    return $Call.ByID(4117878330, req);
}

export function ReadScreenshotImage(req: $models.ScreenshotImageRequest): $CancellablePromise<$models.ScreenshotImageResult> {
    return $Call.ByID(2843762551, req);
}

export function RecoverRecordingPackage(packageDir: string): $CancellablePromise<recpackage$0.RecoverySummary> {
    return $Call.ByID(919661591, packageDir);
}

export function ReselectAnnotationRegion(): $CancellablePromise<$models.RegionSelectionSession> {
    return $Call.ByID(2985632494);
}

export function ResumeRecording(): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(2366067120);
}

export function SaveAnnotationCapture(req: $models.AnnotationCaptureRequest): $CancellablePromise<$models.AnnotationCaptureResult> {
    return $Call.ByID(938219912, req);
}

export function SaveSettings(next: settings$0.Settings): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(35428118, next);
}

export function SaveWhiteboardExport(req: $models.WhiteboardExportRequest): $CancellablePromise<$models.WhiteboardExportResult> {
    return $Call.ByID(3548116314, req);
}

export function SaveWhiteboardScene(req: $models.WhiteboardSceneRequest): $CancellablePromise<$models.WhiteboardSceneResult> {
    return $Call.ByID(1809937380, req);
}

export function ScanRecordingPackages(): $CancellablePromise<recpackage$0.RecoverySummary[] | null> {
    return $Call.ByID(1742539791);
}

export function SetAnnotationOverlayHitRegions(req: $models.CapsuleWindowHitRegionsRequest): $CancellablePromise<void> {
    return $Call.ByID(2215651335, req);
}

export function SetCapsuleWindowHitRegions(req: $models.CapsuleWindowHitRegionsRequest): $CancellablePromise<void> {
    return $Call.ByID(3454285251, req);
}

export function SetDataRoot(rootDir: string): $CancellablePromise<appdata$0.Info> {
    return $Call.ByID(2213117442, rootDir);
}

export function ShowAnnotationOverlay(): $CancellablePromise<$models.AnnotationOverlayState> {
    return $Call.ByID(2906956594);
}

export function ShowAnnotationRegionSelector(): $CancellablePromise<$models.RegionSelectionSession> {
    return $Call.ByID(1624388907);
}

export function ShowPIPOverlay(req: $models.PIPOverlayRequest): $CancellablePromise<$models.PIPOverlayState> {
    return $Call.ByID(1812737360, req);
}

export function ShowPinnedScreenshot(id: string): $CancellablePromise<$models.ScreenshotPinState> {
    return $Call.ByID(1741059049, id);
}

export function ShowRegionSelector(): $CancellablePromise<$models.RegionSelectionSession> {
    return $Call.ByID(2760023242);
}

export function ShowScreenIndicator(req: $models.ScreenIndicatorRequest): $CancellablePromise<$models.ScreenIndicatorResult> {
    return $Call.ByID(1545499612, req);
}

export function ShowScreenshotRegionSelector(): $CancellablePromise<$models.RegionSelectionSession> {
    return $Call.ByID(872220670);
}

export function ShowSettingsWindow(): $CancellablePromise<void> {
    return $Call.ByID(795547170);
}

export function ShowWhiteboardWindow(): $CancellablePromise<void> {
    return $Call.ByID(3067691032);
}

export function StartAudioOnlyRecording(req: recording$0.AudioOnlyRequest): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(3205009257, req);
}

export function StartMicrophoneLevelMonitor(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(4183188046, deviceID);
}

export function StartMockRecording(req: recording$0.StartRequest): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(989661299, req);
}

export function StartRecording(req: recording$0.StartRequest): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(171835981, req);
}

export function StartScrollingScreenshot(): $CancellablePromise<void> {
    return $Call.ByID(3090857805);
}

export function StopMicrophoneLevelMonitor(): $CancellablePromise<void> {
    return $Call.ByID(693365190);
}

export function StopRecording(): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(4017105749);
}

export function ToggleWhiteboardWindow(): $CancellablePromise<void> {
    return $Call.ByID(1949585145);
}

export function UpdatePIPOverlay(req: $models.PIPOverlayRequest): $CancellablePromise<$models.PIPOverlayState> {
    return $Call.ByID(1829978564, req);
}

export function UpdateScreenshotRegionSelection(req: $models.RegionSelectionRequest): $CancellablePromise<$models.RegionFrameState> {
    return $Call.ByID(445412471, req);
}

export function UpdateSelectedRegion(req: $models.RegionSelectionRequest): $CancellablePromise<$models.RegionSelectionResult> {
    return $Call.ByID(22393138, req);
}
