// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appdata$0 from "./internal/appdata/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capture$0 from "./internal/capture/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as devices$0 from "./internal/devices/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as preflight$0 from "./internal/preflight/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recording$0 from "./internal/recording/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recpackage$0 from "./internal/recpackage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "./internal/settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Bootstrap(): $CancellablePromise<$models.BootstrapState> {
    return $Call.ByID(3811015052);
}

export function CancelRegionSelection(): $CancellablePromise<$models.RegionSelectionResult> {
    return $Call.ByID(3597544006);
}

export function CancelSelectedRegion(): $CancellablePromise<$models.RegionSelectionResult> {
    return $Call.ByID(1279436437);
}

export function CompleteRegionSelection(req: $models.RegionSelectionRequest): $CancellablePromise<$models.RegionSelectionResult> {
    return $Call.ByID(1962254349, req);
}

export function ExportRecordingPackage(req: $models.ExportRecordingRequest): $CancellablePromise<$models.ExportRecordingResult> {
    return $Call.ByID(2136941557, req);
}

export function GetCaptureCapabilities(): $CancellablePromise<capture$0.Capabilities> {
    return $Call.ByID(4009257246);
}

export function GetSettings(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1085525119);
}

export function HidePIPOverlay(): $CancellablePromise<void> {
    return $Call.ByID(2267008089);
}

export function HideRegionFrame(): $CancellablePromise<void> {
    return $Call.ByID(1481407147);
}

export function HideScreenIndicator(): $CancellablePromise<void> {
    return $Call.ByID(3727544311);
}

export function HideSettingsWindow(): $CancellablePromise<void> {
    return $Call.ByID(4158023747);
}

export function ListMediaDevices(): $CancellablePromise<devices$0.MediaInventory> {
    return $Call.ByID(2412119741);
}

export function ListSources(): $CancellablePromise<devices$0.CaptureSource[] | null> {
    return $Call.ByID(3137910140);
}

export function OpenRecordingPackage(packageDir: string): $CancellablePromise<recpackage$0.RecoverySummary> {
    return $Call.ByID(339423795, packageDir);
}

export function OpenVideoDirectory(): $CancellablePromise<appdata$0.Info> {
    return $Call.ByID(1462702352);
}

export function PauseRecording(): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(2282766307);
}

export function PreflightAudioOnlyRecording(req: recording$0.AudioOnlyRequest): $CancellablePromise<preflight$0.Summary> {
    return $Call.ByID(992673734, req);
}

export function PreflightRecording(req: recording$0.StartRequest): $CancellablePromise<preflight$0.Summary> {
    return $Call.ByID(2137129988, req);
}

export function RecoverRecordingPackage(packageDir: string): $CancellablePromise<recpackage$0.RecoverySummary> {
    return $Call.ByID(919661591, packageDir);
}

export function ResumeRecording(): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(2366067120);
}

export function SaveSettings(next: settings$0.Settings): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(35428118, next);
}

export function ScanRecordingPackages(): $CancellablePromise<recpackage$0.RecoverySummary[] | null> {
    return $Call.ByID(1742539791);
}

export function SetCapsuleWindowHitRegions(req: $models.CapsuleWindowHitRegionsRequest): $CancellablePromise<void> {
    return $Call.ByID(3454285251, req);
}

export function SetDataRoot(rootDir: string): $CancellablePromise<appdata$0.Info> {
    return $Call.ByID(2213117442, rootDir);
}

export function ShowPIPOverlay(req: $models.PIPOverlayRequest): $CancellablePromise<$models.PIPOverlayState> {
    return $Call.ByID(1812737360, req);
}

export function ShowRegionSelector(): $CancellablePromise<$models.RegionSelectionSession> {
    return $Call.ByID(2760023242);
}

export function ShowScreenIndicator(req: $models.ScreenIndicatorRequest): $CancellablePromise<$models.ScreenIndicatorResult> {
    return $Call.ByID(1545499612, req);
}

export function ShowSettingsWindow(): $CancellablePromise<void> {
    return $Call.ByID(795547170);
}

export function StartAudioOnlyRecording(req: recording$0.AudioOnlyRequest): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(3205009257, req);
}

export function StartMicrophoneLevelMonitor(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(4183188046, deviceID);
}

export function StartMockRecording(req: recording$0.StartRequest): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(989661299, req);
}

export function StartRecording(req: recording$0.StartRequest): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(171835981, req);
}

export function StopMicrophoneLevelMonitor(): $CancellablePromise<void> {
    return $Call.ByID(693365190);
}

export function StopRecording(): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(4017105749);
}

export function UpdatePIPOverlay(req: $models.PIPOverlayRequest): $CancellablePromise<$models.PIPOverlayState> {
    return $Call.ByID(1829978564, req);
}

export function UpdateSelectedRegion(req: $models.RegionSelectionRequest): $CancellablePromise<$models.RegionSelectionResult> {
    return $Call.ByID(22393138, req);
}
