// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appdata$0 from "./internal/appdata/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capture$0 from "./internal/capture/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as devices$0 from "./internal/devices/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as preflight$0 from "./internal/preflight/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recording$0 from "./internal/recording/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recpackage$0 from "./internal/recpackage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "./internal/settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Bootstrap(): $CancellablePromise<$models.BootstrapState> {
    return $Call.ByID(3811015052);
}

export function GetCaptureCapabilities(): $CancellablePromise<capture$0.Capabilities> {
    return $Call.ByID(4009257246);
}

export function GetSettings(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1085525119);
}

export function HideSettingsWindow(): $CancellablePromise<void> {
    return $Call.ByID(4158023747);
}

export function ListMediaDevices(): $CancellablePromise<devices$0.MediaInventory> {
    return $Call.ByID(2412119741);
}

export function ListSources(): $CancellablePromise<devices$0.CaptureSource[] | null> {
    return $Call.ByID(3137910140);
}

export function PauseRecording(): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(2282766307);
}

export function PreflightRecording(req: recording$0.StartRequest): $CancellablePromise<preflight$0.Summary> {
    return $Call.ByID(2137129988, req);
}

export function RecoverRecordingPackage(packageDir: string): $CancellablePromise<recpackage$0.RecoverySummary> {
    return $Call.ByID(919661591, packageDir);
}

export function ResumeRecording(): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(2366067120);
}

export function SaveSettings(next: settings$0.Settings): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(35428118, next);
}

export function ScanRecordingPackages(): $CancellablePromise<recpackage$0.RecoverySummary[] | null> {
    return $Call.ByID(1742539791);
}

export function SetDataRoot(rootDir: string): $CancellablePromise<appdata$0.Info> {
    return $Call.ByID(2213117442, rootDir);
}

export function ShowSettingsWindow(): $CancellablePromise<void> {
    return $Call.ByID(795547170);
}

export function StartAudioOnlyRecording(req: recording$0.AudioOnlyRequest): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(3205009257, req);
}

export function StartMockRecording(req: recording$0.StartRequest): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(989661299, req);
}

export function StartRecording(req: recording$0.StartRequest): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(171835981, req);
}

export function StopRecording(): $CancellablePromise<recording$0.Session> {
    return $Call.ByID(4017105749);
}
