// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AudioEnhancement {
    "engine": string;
    "appliesTo": string;
    "available": boolean;
    "capability": SourceCapability;
    "unavailableReason"?: string;
}

export interface CaptureSource {
    "id": string;
    "type": CaptureSourceType;
    "name": string;
    "subtitle": string;
    "x"?: number;
    "y"?: number;
    "width"?: number;
    "height"?: number;
    "nativeId"?: string;
    "displayIndex"?: number;
    "processId"?: number;
    "available": boolean;
    "capability": SourceCapability;
    "unavailableReason"?: string;
}

export enum CaptureSourceType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SourceScreen = "screen",
    SourceAllScreens = "all-screens",
    SourceRegion = "region",
    SourceWindow = "window",
    SourceApplication = "application",
};

export interface MediaDevice {
    "id": string;
    "type": MediaDeviceType;
    "name": string;
    "subtitle": string;
    "nativeId"?: string;
    "isDefault": boolean;
    "available": boolean;
    "capability": SourceCapability;
    "unavailableReason"?: string;
    "rnnoiseEligible"?: boolean;
    "sidecarEligible"?: boolean;
}

export enum MediaDeviceType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DeviceSystemAudio = "system-audio",
    DeviceMicrophone = "microphone",
    DeviceCamera = "camera",
};

export interface MediaInventory {
    "systemAudio": MediaDevice[] | null;
    "microphones": MediaDevice[] | null;
    "cameras": MediaDevice[] | null;
    "enhancement": AudioEnhancement;
}

export enum SourceCapability {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CapabilityEnumerated = "enumerated",
    CapabilityUnavailable = "unavailable",
    CapabilityNativeQueued = "native-backend-queued",
};
