// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface RecoverySummary {
    "packageDir": string;
    "manifestPath"?: string;
    "status": string;
    "recoverable": boolean;
    "reason"?: string;
}
