// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ManifestAnnotationTarget {
    "type": string;
    "id": string;
    "geometry"?: ManifestSourceGeometry | null;
}

export interface ManifestSourceGeometry {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "displayIndex"?: number;
    "nativeId"?: string;
}

export interface RecoverySummary {
    "packageDir": string;
    "manifestPath"?: string;
    "status": string;
    "recoverable": boolean;
    "reason"?: string;
}
