// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recording$0 from "../recording/models.js";

export interface Check {
    "id": string;
    "label": string;
    "status": Status;
    "reason"?: string;
}

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusReady = "ready",
    StatusWarning = "warning",
    StatusBlocked = "blocked",
};

export interface Summary {
    "status": Status;
    "backend": string;
    "message": string;
    "checks": Check[] | null;
    "normalizedRequest": recording$0.StartRequest;
}
