package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type configCheck struct {
	File    string   `json:"file"`
	Name    string   `json:"name"`
	Needles []string `json:"needles"`
}

type checkResult struct {
	File    string `json:"file"`
	Name    string `json:"name"`
	Status  string `json:"status"`
	Message string `json:"message,omitempty"`
}

type report struct {
	OK          bool          `json:"ok"`
	GeneratedAt time.Time     `json:"generatedAt"`
	Root        string        `json:"root"`
	Checks      []checkResult `json:"checks"`
}

var releaseConfigChecks = []configCheck{
	{
		File: ".github/workflows/ci.yml",
		Name: "CI keeps RNNoise dynamic artifact gates",
		Needles: []string{
			"RNNOISE_TAG: rnnoise_dynamic",
			"Build RNNoise dynamic module",
			"./scripts/build-rnnoise-windows.ps1",
			"./scripts/build-rnnoise-unix.sh",
			"wails3 task windows:build ARCH=\"${{ matrix.arch }}\" EXTRA_TAGS=\"${tags}\"",
			"-require-rnnoise",
			"msys2/setup-msys2@v2",
			"release: true",
			"windows_msystem: MINGW64",
			"mingw-w64-x86_64-gcc",
			"windows_cc_subdir: mingw64",
			"windows_cc_exe: gcc.exe",
			"windows_msystem: CLANGARM64",
			"mingw-w64-clang-aarch64-clang",
			"windows_cc_subdir: clangarm64",
			"windows_cc_exe: clang.exe",
			"steps.msys2.outputs.msys2-location",
			"-Compiler \"$env:CC\"",
			"cgo_enabled: \"0\"",
			"rnnoise_dynamic: \"true\"",
		},
	},
	{
		File: ".github/workflows/ci.yml",
		Name: "CI keeps Windows FFmpeg video gate",
		Needles: []string{
			"./scripts/ensure-windows-ffmpeg.ps1 -Architecture \"${{ matrix.ffmpeg_arch }}\"",
			"-require-video -require-rnnoise",
		},
	},
	{
		File: ".github/workflows/ci.yml",
		Name: "CI runs frontend e2e gates",
		Needles: []string{
			"Install Playwright Chromium",
			"Run frontend e2e",
			"npm run test:e2e",
			"tee frontend-e2e.log",
			"Frontend e2e failed",
			"Clean frontend e2e artifacts before Go tests",
			"rm -rf frontend/test-results frontend/playwright-report frontend/frontend-e2e.log",
			"set +e",
			"tee go-test.log",
			"set -e",
			"GITHUB_STEP_SUMMARY",
			"Go test failed",
		},
	},
	{
		File: "app/frontend/tests/capsule-whiteboard-entry.spec.ts",
		Name: "Frontend e2e fixes whiteboard dual-state entry",
		Needles: []string{
			"opens board before recording and annotation during video recording",
			"remains available as a board during audio recording",
			"expectWhiteboardLaunch(page, 'whiteboard', '/#/whiteboard')",
			"expectWhiteboardLaunch(page, 'annotation', '/#/annotation-overlay')",
			"Pause recording",
			"Resume recording",
			"is-recording-compact",
			"screenshot tools hide window and focused-window capture modes",
			"Window screenshot",
			"Focused window",
			"toHaveCount(0)",
		},
	},
	{
		File: "app/frontend/src/App.tsx",
		Name: "Frontend screenshot tools keep only user-facing OCR capture entries",
		Needles: []string{
			"captureScreenshotMode('full')",
			"beginScrollingScreenshot",
			"copy.screenshot.region",
			"copy.screenshot.full",
			"copy.screenshot.scrolling",
			"copy.whiteboard.open",
		},
	},
	{
		File: "app/frontend/tests/capsule-whiteboard-entry.spec.ts",
		Name: "Frontend e2e covers OCR result and pin flows",
		Needles: []string{
			"floating OCR result panel shows screenshot image blocks and translation guard",
			"floating OCR result panel renders real worker smoke evidence coordinates",
			"screenshot history ready item opens OCR result floating panel with real worker evidence",
			"screenshot history translates ready OCR text through the configured provider",
			"pinned screenshot window restores OCR highlight and result floating panel after resize",
			"pinned screenshot window renders real worker smoke evidence after resize",
			"Translation provider is not configured",
			"Translation copied",
			".ocr-preview-frame polygon",
			"__RF_FORCE_FLOATING_PANEL_WINDOWS__",
			"viewBox', '0 0 900 280'",
			"View OCR result",
			"pin-ocr-ready-shot",
		},
	},
	{
		File: "app/frontend/tests/whiteboard.spec.ts",
		Name: "Frontend e2e covers whiteboard OCR and recording safety",
		Needles: []string{
			"whiteboard selected image OCR queues its own exported image as whiteboard-selection",
			"whiteboard OCR blocks map to the selected image and recognized text inserts as scene text",
			"whiteboard OCR blocks and recognized text persist after reopen",
			"whiteboard selected image OCR opens result panel with its exported image",
			"whiteboard selected image OCR result panel renders real worker smoke evidence coordinates",
			"whiteboard translated OCR text inserts as scene text after explicit provider configuration",
			"whiteboard OCR failure during an audio recording does not stop the recorder shell",
			"sourceKind: 'whiteboard-selection'",
			"View board OCR result",
			"viewBox', '0 0 320 180'",
			"viewBox', '0 0 900 280'",
			"30.133928571428573,32.083333333333336 669.9776785714286,32.083333333333336 669.9776785714286,109.86111111111113 30.133928571428573,109.86111111111113",
			"41.34375,137.08333333333334 330.3080357142857,137.08333333333334 330.3080357142857,234.30555555555557 41.34375,234.30555555555557",
			"recordingFreedomOcr",
			"OCR blocks hidden",
		},
	},
	{
		File: "app/frontend/tests/annotation-overlay.spec.ts",
		Name: "Frontend e2e covers recording annotation OCR safety",
		Needles: []string{
			"recording annotation overlay queues background OCR and opens result panel",
			"Recognize board text",
			"sourceKind: 'whiteboard'",
			"priority: 'background'",
			"View board OCR result",
			"annotation-ocr-result",
		},
	},
	{
		File: "app/frontend/tests/shortcut-settings.spec.ts",
		Name: "Frontend e2e covers OCR settings",
		Needles: []string{
			"settings exposes local OCR model package management",
			"settings downloads a verified OCR model package without auto-switching active model",
			"settings refreshes the verified OCR model catalog before manual download",
			"settings confirms before switching the active OCR model",
			"settings keeps the current OCR model when a confirmed switch fails",
			"settings persists explicit OCR translation provider configuration",
			"ppocrv5-mobile-zh-en",
			"ppocrv6-mobile-zh-en",
			"ppocrv6-medium-zh-en",
			"Model package .zip or extracted folder path",
			"OCR model package import is local-only",
			"__RF_LAST_OCR_MODEL_DOWNLOAD__",
			"__RF_LAST_OCR_MODEL_CATALOG_REFRESH__",
			"Refresh catalog",
			"Confirm switch",
			"__RF_LAST_SET_ACTIVE_OCR_MODEL__",
			"OpenAI-compatible",
			"Allow sending OCR text for translation",
		},
	},
	{
		File: "app/frontend/src/App.tsx",
		Name: "Frontend OCR result panel emits desktop render evidence logs",
		Needles: []string{
			"logClientEvent('ocr-result', 'preview-loaded'",
			"logClientEvent('ocr-result', 'rendered'",
			"logClientEvent('ocr-result', 'copy-block'",
			"logClientEvent('ocr-result', 'translation-rendered'",
			"polygonCount",
			"hasPreview: true",
			"result?.plainText.trim()",
		},
	},
	{
		File: "app/internal/ocr/service_test.go",
		Name: "Go OCR tests protect translation cache and scrolling tiles",
		Needles: []string{
			"TestTranslateDisabledProviderDoesNotCallNetwork",
			"TestTranslateOpenAICompatibleWritesAndReadsCache",
			"TestTranslateDeepLSegments",
			"TestTranslateRejectsSegmentMismatchWithoutCache",
			"TestRecognizeScrollingScreenshotUsesTilesAndDedupesOverlap",
			"TestRefreshModelCatalogSavesVerifiedPackageRegistry",
			"TestRefreshModelCatalogRejectsUnsupportedModel",
			"TestStartModelDownloadInstallsVerifiedPackageAndDoesNotActivate",
			"TestStartModelDownloadRejectsChecksumMismatchWithoutInstall",
			"TestCancelModelDownloadStopsTransferWithoutInstall",
			"TestRetryModelDownloadAfterCancelInstallsWithoutAutoSwitch",
			"TestDefaultModelRegistryMatchesThirdPartyManifest",
			"TestDefaultModelRegistryExposesPPocrV6SourceDownloadWithoutCls",
			"TestStartModelDownloadInstallsPinnedSourceFilesAndGeneratedKeys",
			"TestStartModelDownloadRejectsGeneratedKeysMismatchWithoutInstall",
			"TestRemoveInactiveModelKeepsActiveModel",
			"TestRemoveActiveModelFallsBackToDefaultModel",
			"TestInstallModelPackageAllowsMissingClsWhenTextlineOrientationDisabled",
			"TestParseModelCatalogAllowsMissingClsWhenTextlineOrientationDisabled",
			"TestParseModelCatalogRejectsMissingClsByDefault",
			"ModelDownloadCancelled",
			"modelDownloadStagingPrefix",
			"TextlineOrientationNone",
			"translationsDir()",
		},
	},
	{
		File: "app/internal/ocr/registry.go",
		Name: "OCR service exposes runtime options for desktop smoke tools",
		Needles: []string{
			"ServiceOptions",
			"NewServiceWithOptions",
			"ApplyOptions",
			"WorkerPath",
			"RuntimeDir",
			"WorkerArgs",
			"WorkerCapabilitiesArgs",
			"WorkerEnv",
			"WorkerTimeout",
			"ModelRegistry",
		},
	},
	{
		File: "app/internal/ocr/worker.go",
		Name: "OCR worker child processes run hidden in the desktop app",
		Needles: []string{
			"exec.CommandContext(ctx, workerPath, args...)",
			"exec.CommandContext(ctx, workerPath, s.workerArgs...)",
			"configureBackgroundCommand(cmd)",
		},
	},
	{
		File: "app/internal/ocr/process_windows.go",
		Name: "Windows OCR worker process hides console windows",
		Needles: []string{
			"HideWindow:    true",
			"CreationFlags: windowsCreateNoWindow",
			"0x08000000",
		},
	},
	{
		File: "app/services.go",
		Name: "Desktop path open commands run hidden",
		Needles: []string{
			"exec.Command(command, args...)",
			"configureBackgroundCommand(cmd)",
			"exec.Command(\"rundll32.exe\", \"url.dll,FileProtocolHandler\", absoluteTarget)",
			"configureBackgroundCommand(fallback)",
		},
	},
	{
		File: "app/process_windows.go",
		Name: "Windows app helper hides spawned command windows",
		Needles: []string{
			"HideWindow:    true",
			"CreationFlags: windowsCreateNoWindow",
			"0x08000000",
		},
	},
	{
		File: "app/cmd/ocr-worker/main_test.go",
		Name: "OCR worker tests protect optional textline orientation mode",
		Needles: []string{
			"TestInitAllowsMissingClsWhenTextlineOrientationDisabled",
			"validateModelDir",
			"modelSessionSpecs",
			"TextlineOrientationNone",
			"det and rec only",
		},
	},
	{
		File: "app/screenshot_test.go",
		Name: "Go screenshot tests protect no-scroll OCR fallback",
		Needles: []string{
			"TestCaptureScrollingScreenshotStaticTargetQueuesRegionOCR",
			"TestCancelledOCRJobEventDoesNotAllowLateReadyHistoryState",
			"TestWhiteboardSelectionOCRJobEventUpdatesHistory",
			"captureScrollingScreenshotWith",
			"SourceRegionScreenshot",
			"SourceWhiteboardSelection",
			"want region for static scrolling target fallback",
			"late ready after cancel",
			"want region-screenshot for no-scroll fallback",
		},
	},
	{
		File: "app/screenshot_test.go",
		Name: "Go screenshot smoke covers real long scrolling OCR evidence",
		Needles: []string{
			"TestScreenshotOCRRealWorkerSmoke",
			"TestWhiteboardSelectionOCRRealWorkerSmoke",
			"buildLongOCRSmokeImage",
			`scenario: "scrolling-long"`,
			`"whiteboard-selection-real-worker"`,
			"SourceWhiteboardSelection",
			"writeWhiteboardOCRSmokeEvidence",
			"long scrolling OCR height",
			"want tiled long image height > 2400",
			"CacheHitWithoutWorker",
		},
	},
	{
		File: "app/cmd/ocr-smoke-evidence-check/main.go",
		Name: "OCR smoke evidence checker protects real worker artifacts",
		Needles: []string{
			"requiredScenarios",
			"requiredWhiteboardScenarios",
			"whiteboard-ocr-real-worker-smoke.json",
			"whiteboard-selection-real-worker",
			"elementId is required for whiteboard-selection evidence",
			"expected-model",
			"defaultExpectedModelID",
			"runWithExpectedModel",
			"region-queued-cache-hit",
			"scrolling-long imageHeight",
			"cacheHitWithoutWorker",
			"queuedCacheHit",
			"must stay inside evidence directory",
			"RecordingFreedom",
			"文字识别",
		},
	},
	{
		File: "app/cmd/ocr-desktop-evidence-check/main.go",
		Name: "OCR desktop evidence checker fixes real Wails acceptance contract",
		Needles: []string{
			"internal/ocrevidence",
			"ocrevidence.RequiredSourceKinds",
			"ocrevidence.MatchVisualRequirements",
			"VisualRequirementMatch",
			"README.md",
			"validateKnownFailuresAreClear",
			"known failures must be none",
			"platform.txt",
			"app-log.jsonl",
			"ocr-job-events.jsonl",
			"export-report.json",
			"data-root-precheck.json",
			"validateDataRootPrecheck",
			"app-log run window",
			"validateAppLogRunWindow",
			"desktop evidence session",
			"validateSessionMarkers",
			"EvidenceSessionComponent",
			"EvidenceSessionStartEvent",
			"EvidenceSessionEndEvent",
			"outside data-root precheck app event window",
			"validateExportReport",
			"appLogLines",
			"jobEventLines",
			"visual evidence",
			"visual-manifest.json",
			"visual-capture-checklist",
			"validateVisualCaptureChecklist",
			"DataRootPrecheck",
			"ChecklistMarkdown",
			"ChecklistJSON",
			"VisualRequirements",
			"VisualDimensionFailures",
			"ExistingVisualDimensions",
			"loadVisualManifest",
			"validateVisualManifestEntry",
			"sha256 mismatch",
			"dimensions",
			"requires at least",
			"floating-panel",
			"ocr-result",
			"annotation-overlay",
			"save-capture",
			"annotationCapturePackages",
			"annotationBackgroundQueueSources",
			"JobPriorityBackground",
			"hasSharedKey",
			"sourceId matching annotation-overlay/save-capture packageDir",
			"evidence chain",
			"validateEvidenceChain",
			"validateScopedJobEvents",
			"requiredResultsByKind",
			"appLogHasResultEvent",
			"jobEventsHaveQueued",
			"jobEventsHaveReady",
			"desktop OCR evidence chain is inconsistent",
			"unexpected resultId",
			"duplicate OCR result sourceKind",
			"queue-request",
			"openResultSources",
			"readImageSources",
			"clientPreviewSources",
			"clientRenderedSources",
			"open-result",
			"read-result-image",
			"client.ocr-result",
			"preview-loaded",
			"rendered",
			"hasPreview",
			"polygonCount",
			"translate-request",
			"translate-ready",
			"require-translation",
			"must-contain",
			"evidence image path",
			"must stay inside",
			"outside image",
		},
	},
	{
		File: "app/cmd/ocr-desktop-evidence-check/main_test.go",
		Name: "OCR desktop evidence checker tests protect required sources and geometry",
		Needles: []string{
			"internal/ocrevidence",
			"ocrevidence.RequiredSourceKinds",
			"ocrevidence.MatchVisualRequirements",
			"TestRunAcceptsCompleteDesktopOCREvidence",
			"TestRunRejectsMissingDesktopOCRSourceKind",
			"TestRunRejectsOutOfBoundsOCRBlock",
			"TestRunRejectsAppLogResultChainMismatch",
			"TestRunRejectsJobEventResultChainMismatch",
			"TestRunRejectsUnexpectedScopedJobEvent",
			"TestRunRejectsDuplicateOCRResultSourceKind",
			"TestRunRejectsMissingOCROperationAppLog",
			"TestRunRejectsMissingPerSourceResultReadLog",
			"TestRunRejectsMissingRecordingAnnotationOperationLog",
			"TestRunRejectsRecordingAnnotationQueueNotTiedToSavedPackage",
			"TestRunRejectsKnownFailures",
			"TestRunRejectsTamperedVisualManifest",
			"TestRunRejectsMismatchedExportReport",
			"TestRunRejectsMissingVisualRequirement",
			"TestRunRejectsTooSmallVisualRequirement",
			"TestRunRejectsMissingVisualCaptureChecklist",
			"TestRunRejectsMissingDataRootPrecheck",
			"TestRunRejectsAppLogOutsideDataRootPrecheckWindow",
			"TestRunRejectsMissingEvidenceSessionMarkers",
			"checker-session",
			"writeVisualManifest",
			"writeDesktopChecklist",
			"makeFixtureDataRootPrecheck",
			"sha256 mismatch",
			"resultCount",
			"recording-annotation-ocr-safety.png",
			"createDesktopOCREvidence",
			"requireTranslation: true",
			"ocr/queue-request sourceKind=region-screenshot",
			"ocr/open-result sourceKind=region-screenshot",
			"ocr/read-result-image sourceKind=region-screenshot",
			"client.ocr-result/preview-loaded sourceKind=region-screenshot",
			"client.ocr-result/rendered sourceKind=region-screenshot",
			"annotation-overlay/show packageDir",
			"annotation-overlay/save-capture packageDir bytes",
			"ocr/queue-request sourceKind=whiteboard priority=background sourceId",
			"RecordingFreedom",
			"文字识别",
			"whiteboard-selection",
			"outside image",
		},
	},
	{
		File: "app/cmd/ocr-desktop-evidence-export/main.go",
		Name: "OCR desktop evidence exporter builds checker-ready packages",
		Needles: []string{
			"internal/ocrevidence",
			"ocrevidence.RequiredSourceKinds",
			"ocrevidence.MatchVisualRequirements",
			"VisualRequirementMatch",
			"visual-dir",
			"data-root",
			"-data-root is required",
			"same RecordingFreedom data root passed to ocr-desktop-evidence-session",
			"platform-file",
			"app-log.jsonl",
			"ocr-job-events.jsonl",
			"copyVisualEvidence",
			"visual-manifest.json",
			"visual-capture-checklist.md",
			"visual-capture-checklist.json",
			"writeVisualCaptureChecklist",
			"NewChecklistReport",
			"MarkdownChecklist",
			"VisualRequirements",
			"matchVisualRequirements",
			"visualManifestEntry",
			"fileSHA256",
			"imageSize",
			"exportResults",
			"managedDataRootFile",
			"include-translations",
			"must stay inside data root",
			"export-report.json",
			"data-root-precheck.json",
			"AuditDataRoot",
			"DataRootPrecheck",
			"copyJSONLLinesInWindow",
			"copyScopedJobEvents",
			"jobEventRequirements",
			"scopedJobEventKey",
			"appLogLineTimestamp",
		},
	},
	{
		File: "app/cmd/ocr-desktop-evidence-export/main_test.go",
		Name: "OCR desktop evidence exporter tests protect real-data package assembly",
		Needles: []string{
			"internal/ocrevidence",
			"ocrevidence.RequiredSourceKinds",
			"ocrevidence.RequiredVisualEvidence",
			"TestRunExportsDesktopOCREvidenceFromDataRoot",
			"TestRunExportedEvidencePassesDesktopEvidenceChecker",
			"exec.Command",
			"../ocr-desktop-evidence-check",
			"-must-contain",
			"TestRunRejectsNonImageVisualEvidence",
			"TestRunRejectsMissingRequiredVisualScene",
			"TestRunRejectsTooSmallVisualEvidence",
			"TestRunRejectsMissingVisualEvidenceDirectory",
			"TestRunRejectsMissingDataRoot",
			"-data-root is required",
			"expectedAppLogLines",
			"createDesktopDataRoot",
			"createVisualEvidence",
			"visual-manifest.json",
			"recording-annotation-ocr-safety.png",
			"not a decodable image",
			"ocr-job-events.jsonl",
			"app-log.jsonl",
			"data-root-precheck.json",
			"sessionId",
			"export-session",
			"historical-window-poison",
			"historical-job-poison",
			"RecordingFreedom",
			"文字识别",
			"images/",
			"visual-capture-checklist.md",
			"visual-capture-checklist.json",
			"EvidenceChainRequirements",
			"DataRootPrecheck",
		},
	},
	{
		File: "app/cmd/ocr-desktop-evidence-session/main.go",
		Name: "OCR desktop evidence session tool writes real-run markers",
		Needles: []string{
			"internal/ocrevidence",
			"ocr-desktop-evidence session report",
			"data-root",
			"event",
			"session-id",
			"timestamp",
			"normalizeEvent",
			"EvidenceSessionStartEvent",
			"EvidenceSessionEndEvent",
			"WriteSessionMarker",
			"appdata.NewService",
		},
	},
	{
		File: "app/cmd/ocr-desktop-evidence-session/main_test.go",
		Name: "OCR desktop evidence session tests protect start end markers",
		Needles: []string{
			"TestRunWritesStartAndEndMarkers",
			"TestRunRequiresSessionIDForEnd",
			"recordingfreedom-2026-07-06.log",
			"session-start",
			"session-end",
			"session-test",
			"ocr-desktop-evidence",
		},
	},
	{
		File: "app/internal/ocrevidence/contract.go",
		Name: "OCR desktop evidence contract is shared by checker exporter and plan",
		Needles: []string{
			"RequiredSourceKinds",
			"SourceRegionScreenshot",
			"SourceFullScreenshot",
			"SourceScrollingScreenshot",
			"SourcePinnedScreenshot",
			"SourceWhiteboard",
			"SourceWhiteboardSelection",
			"RequiredVisualEvidence",
			"EvidenceChainRequirements",
			"EvidenceSessionRunbook",
			"same data-root",
			"Do not create session markers during export",
			"VisualRequirement",
			"VisualRequirementMatch",
			"VisualFileDimension",
			"MinWidth",
			"MinHeight",
			"RecommendedFile",
			"region-screenshot-capture.png",
			"full-screen-capture.png",
			"scrolling-screenshot-capture.png",
			"recording-annotation-ocr-safety.png",
			"MatchVisualRequirements",
			"VisualRequirementMatchPath",
			"VisualFileMatchesRequirement",
			"VisualDimensionFailures",
			"visual evidence is missing files",
			"Exclude",
		},
	},
	{
		File: "app/internal/ocrevidence/session.go",
		Name: "OCR desktop evidence session contract writes app log markers",
		Needles: []string{
			"EvidenceSessionComponent",
			"EvidenceSessionStartEvent",
			"EvidenceSessionEndEvent",
			"SessionMarkerReport",
			"NewSessionID",
			"WriteSessionMarker",
			"recordingfreedom-",
			"sessionId",
			"goos",
			"goarch",
		},
	},
	{
		File: "app/internal/ocrevidence/data_root_precheck.go",
		Name: "OCR desktop evidence data root precheck protects real run logs",
		Needles: []string{
			"DataRootPrecheckReport",
			"DataRootPrecheckRunWindow",
			"DataRootPrecheckSession",
			"DataRootPrecheckSource",
			"DataRootAnnotationPrecheck",
			"AuditDataRoot",
			"dataRootEvidenceSession",
			"dataRootSessionWrapsRunWindow",
			"ocr-desktop-evidence session-start/session-end markers",
			"dataRootMaxEvidenceSpan",
			"dataRootAppEventWindowPadding",
			"createdAt span exceeds evidence window max",
			"app-log timestamp outside OCR evidence window",
			"logs",
			"recordingfreedom-*.log",
			"ocr-job-events.jsonl",
			"data",
			"ocr",
			"results",
			"queue-request",
			"open-result",
			"read-result-image",
			"preview-loaded",
			"rendered",
			"annotation-overlay",
			"save-capture",
			"priority=background",
			"matching save-capture packageDir",
		},
	},
	{
		File: "app/internal/ocrevidence/data_root_precheck_test.go",
		Name: "OCR desktop evidence data root precheck tests protect missing chain detection",
		Needles: []string{
			"TestAuditDataRootAcceptsCompleteDesktopOCRChain",
			"TestAuditDataRootReportsMissingPerSourceClientRender",
			"TestAuditDataRootReportsRecordingAnnotationMismatch",
			"TestAuditDataRootRejectsMixedHistoricalResultRuns",
			"TestAuditDataRootRejectsAppLogEventsWithoutTimestamps",
			"TestAuditDataRootRejectsMissingEvidenceSession",
			"TestAuditDataRootRejectsEventsOutsideEvidenceSession",
			"writeCompleteDataRootFixture",
			"session-test",
			"missing client rendered sourceKind=whiteboard-selection",
			"OCR result createdAt span exceeds evidence window max",
			"missing app-log timestamp",
			"matching save-capture packageDir",
			"RequiredSourceKinds",
		},
	},
	{
		File: "app/internal/ocrevidence/checklist.go",
		Name: "OCR desktop evidence checklist is shared by plan and exporter",
		Needles: []string{
			"ChecklistReport",
			"NewChecklistReport",
			"NewChecklistReportWithDimensions",
			"DataRootPrecheck",
			"session id",
			"session window",
			"MarkdownChecklist",
			"MatchAndMissingVisualRequirements",
			"ExistingVisualDimensions",
			"VisualDimensionFailures",
			"minimum size",
			"EvidenceSessionRunbook",
			"RequiredSourceKindStrings",
			"EvidenceChainRequirements",
			"evidenceChainRequirements",
			"Session boundary runbook",
			"ocr-desktop-evidence-session.exe -event start",
			"visual-capture-checklist.md",
			"visual-capture-checklist.json",
			"Do not create placeholder images",
			"Capture each scene from a real app run",
			"Capture runbook",
			"Evidence chain requirements",
		},
	},
	{
		File: "app/internal/ocrevidence/contract_test.go",
		Name: "OCR desktop evidence contract tests prevent visual scene drift",
		Needles: []string{
			"TestDesktopEvidenceRequirementsExcludeHiddenWindowCaptureEntries",
			"TestMatchVisualRequirementsAcceptsCompleteChecklist",
			"TestVisualDimensionFailuresRejectsTinyPlaceholderImages",
			"TestVisualFileMatchesRequirementHonorsExclusions",
			"TestRequiredCaptureStepsCoverDesktopOCRAcceptance",
			"TestEvidenceChainRequirementsProtectResultIdentity",
			"RequiredVisualEvidence",
			"RequiredCaptureSteps",
			"EvidenceChainRequirements",
			"CaptureStep",
			"MatchVisualRequirements",
			"VisualFileMatchesRequirement",
			"SourceWindowScreenshot",
			"SourceFocusedWindowScreenshot",
			"whiteboard OCR requirement should exclude whiteboard-selection",
		},
	},
	{
		File: "app/cmd/ocr-desktop-evidence-plan/main.go",
		Name: "OCR desktop evidence plan emits executable real-run checklist",
		Needles: []string{
			"internal/ocrevidence",
			"visual-dir",
			"data-root",
			"out-dir",
			"format",
			"check",
			"-data-root is required when -check is used with -visual-dir",
			"same RecordingFreedom data root passed to ocr-desktop-evidence-session start/end",
			"visual-capture-checklist.md",
			"visual-capture-checklist.json",
			"NewChecklistReport",
			"NewChecklistReportWithDimensions",
			"AuditDataRoot",
			"MarkdownChecklist",
			"CheckComplete",
			"scanVisualDir",
			"imageSize",
			"not a decodable image",
			"isIgnoredVisualMetadataFile",
		},
	},
	{
		File: "app/cmd/ocr-desktop-evidence-plan/main_test.go",
		Name: "OCR desktop evidence plan tests protect checklist precheck behavior",
		Needles: []string{
			"TestRunWritesChecklistAndAcceptsCompleteVisualDir",
			"TestRunReportsMissingVisualRequirements",
			"TestRunReportsTooSmallVisualRequirement",
			"TestRunWritesDataRootPrecheck",
			"TestRunReportsIncompleteDataRootPrecheck",
			"TestRunCheckRejectsVisualDirWithoutDataRoot",
			"TestRunRejectsNonImageVisualPrecheck",
			"TestMarkdownChecklistIncludesRecommendedFilenames",
			"TestPlanIncludesExecutableCaptureRunbook",
			"RequiredVisualEvidence",
			"RequiredCaptureSteps",
			"EvidenceChainRequirements",
			"RecommendedFile",
			"Session boundary runbook",
			"evidenceSessionRunbook",
			"ocr-desktop-evidence-session.exe -event start",
			"Do not create session markers during export",
			"Capture runbook",
			"Evidence chain requirements",
			"evidenceChainRequirements",
			"No duplicate sourceKind",
			"visual-capture-checklist.md",
			"visual-capture-checklist.json",
			"recording annotation OCR safety",
			"CheckComplete",
			"MissingVisualRequirements",
			"VisualDimensionFailures",
			"existingVisualDimensions",
			"dataRootPrecheck",
			"sessionId",
		},
	},
	{
		File: "scripts/export-ocr-desktop-evidence.ps1",
		Name: "Windows OCR desktop evidence script exports and checks real runs",
		Needles: []string{
			"VisualDir",
			"ToolsDir",
			"ocr-desktop-evidence-export",
			"ocr-desktop-evidence-check",
			"ocr-desktop-evidence-plan",
			"ocr-desktop-evidence-session",
			"ocr-desktop-evidence-export.exe",
			"ocr-desktop-evidence-check.exe",
			"ocr-desktop-evidence-plan.exe",
			"ocr-desktop-evidence-session.exe",
			"-visual-dir",
			"-data-root",
			"DataRoot is required",
			"$resolvedDataRoot = Resolve-FullPath $DataRoot",
			"RecordingFreedom data root does not exist",
			`"-data-root", $resolvedDataRoot`,
			"-out-dir",
			"-check",
			"visual-capture-checklist",
			"-platform-file",
			"-include-translations=false",
			"RequireTranslation",
			"MustContain",
			"check-report.json",
			"Set-Content -LiteralPath $checkReportPath",
			"report saved to $checkReportPath",
			"OCR desktop evidence exported and checked",
		},
	},
	{
		File: "scripts/export-ocr-desktop-evidence.sh",
		Name: "Unix OCR desktop evidence script exports and checks real runs",
		Needles: []string{
			"--visual-dir",
			"--tools-dir",
			"use_packaged_tools",
			"ocr-desktop-evidence-export",
			"ocr-desktop-evidence-check",
			"ocr-desktop-evidence-plan",
			"ocr-desktop-evidence-session",
			"-platform-file",
			"-data-root",
			"--data-root is required",
			`data_root="$(abs_path "${data_root}")"`,
			"RecordingFreedom data root does not exist",
			`"-data-root" "${data_root}"`,
			"-out-dir",
			"-check",
			"visual-capture-checklist",
			"-include-translations=false",
			"--require-translation",
			"--must-contain",
			"abs_path()",
			"check-report.json",
			"> \"${check_report}\"",
			"report saved to ${check_report}",
			"system_profiler SPDisplaysDataType",
			"xrandr --current",
			"OCR desktop evidence exported and checked",
		},
	},
	{
		File: "app/ocr.go",
		Name: "OCR job events persist desktop evidence JSONL",
		Needles: []string{
			"writeOCRJobEvidenceEvent",
			"logOCRRecognizeRequest",
			"logOCRTranslateRequest",
			"queue-request",
			"open-result",
			"read-result-image",
			"translate-request",
			"ocrEvidenceDir",
			"ocr-job-events.jsonl",
			"data",
			"ocr",
			"evidence",
			"Event      string",
			"event.Event = strings.TrimSpace(name)",
			"os.O_CREATE|os.O_APPEND|os.O_WRONLY",
		},
	},
	{
		File: "app/services_test.go",
		Name: "Go service tests protect OCR job evidence persistence",
		Needles: []string{
			"TestOCRJobEventsPersistEvidenceJSONL",
			"TestOCROperationLogsPersistSafeDesktopEvidence",
			"ocr.job.queued",
			"ocr.job.finished",
			"queue-request",
			"read-result-image",
			"translate-request",
			"sk-secret",
			"ocr-job-events.jsonl",
			"ResultStatusQueued",
			"ResultStatusReady",
			"RecordingFreedom",
			"文字识别",
		},
	},
	{
		File: "app/cmd/ocr-model-lifecycle-smoke/main.go",
		Name: "OCR model lifecycle smoke verifies candidate switch and stable fallback",
		Needles: []string{
			"ocr-model-lifecycle-smoke.json",
			"ServiceOptions",
			"stable-package",
			"candidate-package",
			"install-candidate-no-auto-activate",
			"activate-candidate",
			"recognize-candidate",
			"remove-candidate-fallback-stable",
			"recognize-stable-after-candidate-remove",
			"SetActiveModel",
			"RemoveModel",
			"Force:      true",
			"RecordingFreedom",
			"文字识别",
		},
	},
	{
		File: "app/cmd/ocr-worker-platform-smoke/main.go",
		Name: "OCR worker platform smoke verifies capabilities and stable recognition",
		Needles: []string{
			"ocr-worker-platform-smoke.json",
			"worker-path",
			"runtime-dir",
			"model-package",
			"runCapabilities",
			"runSmoke",
			"RuntimeAvailable",
			"SupportsRecognize",
			"CandidateCount",
			"RecordingFreedom",
			"文字识别",
			"unsafe zip path",
		},
	},
	{
		File: "scripts/run-local-ocr-smoke.ps1",
		Name: "Local OCR smoke validates generated evidence",
		Needles: []string{
			".\\cmd\\ocr-smoke-evidence-check",
			"RF_OCR_WHITEBOARD_SMOKE",
			"Test(ScreenshotOCRRealWorkerSmoke|WhiteboardSelectionOCRRealWorkerSmoke)",
			"whiteboard-ocr-real-worker-smoke.json",
			"-evidence-dir $evidenceDir",
			"-expected-model $Model",
			"IncludeCandidates",
			"-include-candidates",
			"OCR smoke evidence check failed",
		},
	},
	{
		File: "app/services_test.go",
		Name: "Go service tests protect OCR translation secret storage",
		Needles: []string{
			"TestPatchSettingsPreferencesStoresOCRTranslationAPIKeyOutsideSettings",
			"TestTranslateOcrUsesStoredOCRTranslationAPIKey",
			"TestTranslateOcrServiceUsesStoredKeyAndCachesOpenAICompatibleEndpoint",
			"settings file contains raw OCR translation API key",
			"Bearer \"+apiKey",
			"/chat/completions",
			"TranslateOcr(cache hit after provider closed)",
		},
	},
	{
		File: "app/cmd/ocr-translation-smoke/main.go",
		Name: "OCR translation smoke verifies secret-backed provider cache",
		Needles: []string{
			"translation-smoke.json",
			"provider-mode",
			"external-openai-compatible",
			"api-key-env",
			"RF_OCR_TRANSLATION_API_KEY",
			"secretstore.NewStore",
			"httptest.NewServer",
			"ocrService.WriteResult",
			"ocrService.Translate",
			"settingsJsonContainsRawKey",
			"FirstRequestForced",
			"ExternalProviderCacheHitNoAPIKey",
			"ProviderRequestCount",
			"ProviderAuthHeaderOK",
			"ProviderRequestVerified",
			"CacheHitAfterProviderDown",
			"sanitizeBaseURLForReport",
			"translationBlockEvidence",
			"/chat/completions",
			"RecordingFreedom",
			"文字识别",
		},
	},
	{
		File: "app/cmd/ocr-secret-store-smoke/main.go",
		Name: "OCR secret store smoke verifies platform save load delete",
		Needles: []string{
			"secret-store-smoke.json",
			"secretstore.NewStore",
			"store.Save",
			"store.Load",
			"store.Delete",
			"RawSecretInDataRoot",
			"LoadAfterDeleteFound",
			"scanForRawSecret",
			"runtime.GOOS",
			"runtime.GOARCH",
			"rf-secret-store-smoke-value",
		},
	},
	{
		File: ".github/workflows/ci.yml",
		Name: "CI runs OCR translation smoke",
		Needles: []string{
			"Run OCR translation smoke",
			"go run -tags gtk3 ./cmd/ocr-translation-smoke",
		},
	},
	{
		File: ".github/workflows/ci.yml",
		Name: "CI runs OCR secret store smoke across validate and desktop matrix",
		Needles: []string{
			"Run OCR secret store smoke",
			"go run ./cmd/ocr-secret-store-smoke",
			"Run platform OCR secret store smoke",
			"../release-out/ocr-secret-store-smoke/${{ matrix.name }}",
			"Upload OCR secret store smoke evidence",
			"recordingfreedom-ocr-secret-store-smoke-${{ matrix.name }}",
			"secret-store-smoke.json",
		},
	},
	{
		File: ".github/workflows/release.yml",
		Name: "Release Gate runs OCR translation smoke",
		Needles: []string{
			"Run OCR translation smoke",
			"go run -tags gtk3 ./cmd/ocr-translation-smoke",
		},
	},
	{
		File: ".github/workflows/release.yml",
		Name: "Release builds run OCR secret store smoke across platforms",
		Needles: []string{
			"Run OCR secret store smoke",
			"go run ./cmd/ocr-secret-store-smoke",
			"Run platform OCR secret store smoke",
			"../release-out/ocr-secret-store-smoke/${{ matrix.name }}",
		},
	},
	{
		File: "app/internal/secrets/keychain_darwin.go",
		Name: "macOS OCR translation secrets use native Keychain",
		Needles: []string{
			"#cgo LDFLAGS: -framework Security -framework CoreFoundation",
			"SecKeychainAddGenericPassword",
			"SecKeychainFindGenericPassword",
			"SecKeychainItemModifyAttributesAndData",
			"SecKeychainItemDelete",
			"macos-keychain",
		},
	},
	{
		File: "app/internal/secrets/secretservice_linux.go",
		Name: "Linux OCR translation secrets prefer freedesktop Secret Service",
		Needles: []string{
			"secretServiceName",
			"org.freedesktop.secrets",
			"secretServiceIface",
			"org.freedesktop.Secret.Service",
			"secretServiceFallbackName",
			"linux-secret-service+local-file-0600-fallback",
			"OpenSession",
			"CreateItem",
			"SearchItems",
			"GetSecrets",
			"local-file-0600",
		},
	},
	{
		File: ".github/workflows/ci.yml",
		Name: "CI builds desktop smoke tools",
		Needles: []string{
			"Build desktop smoke tools",
			"desktop-doctor${ext}",
			"video-smoke${ext}",
			"audio-smoke${ext}",
			"pip-export-smoke${ext}",
			"annotation-export-smoke${ext}",
			"annotation-overlay-evidence-check${ext}",
			"ocr-desktop-evidence-export${ext}",
			"ocr-desktop-evidence-check${ext}",
			"ocr-desktop-evidence-plan${ext}",
			"ocr-desktop-evidence-session${ext}",
			"ocr-translation-smoke${ext}",
			"ocr-secret-store-smoke${ext}",
		},
	},
	{
		File: ".github/workflows/ci.yml",
		Name: "CI builds OCR worker for each desktop architecture",
		Needles: []string{
			"Build OCR worker",
			"tools/ocr-worker/${worker_goos}-${{ matrix.arch }}",
			"CGO_ENABLED=0 GOOS=\"${worker_goos}\" GOARCH=\"${{ matrix.arch }}\" go build",
			"./cmd/ocr-worker",
		},
	},
	{
		File: ".github/workflows/ci.yml",
		Name: "CI runs platform OCR worker stable smoke across desktop matrix",
		Needles: []string{
			"Build stable OCR model package for platform smoke",
			"Run platform OCR worker stable smoke",
			"./cmd/ocr-model-package -model ppocrv5-mobile-zh-en",
			"./cmd/ocr-worker-platform-smoke",
			"tools/ocr-worker/${worker_goos}-${{ matrix.arch }}/rf-ocr-worker${ext}",
			"tools/onnxruntime/${worker_goos}-${{ matrix.arch }}",
			"recordingfreedom-ocr-worker-platform-smoke-${{ matrix.name }}",
			"ocr-worker-platform-smoke.json",
			"Stable OCR model package was not produced for platform smoke.",
		},
	},
	{
		File: ".github/workflows/ci.yml",
		Name: "CI prepares ONNX Runtime for OCR worker preflight",
		Needles: []string{
			"Prepare Windows ONNX Runtime",
			"./scripts/ensure-windows-onnxruntime.ps1 -Architecture \"${{ matrix.ffmpeg_arch }}\"",
			"Prepare Unix ONNX Runtime",
			"./scripts/ensure-unix-onnxruntime.sh --platform \"${{ matrix.platform }}\" --arch \"${{ matrix.ffmpeg_arch }}\"",
		},
	},
	{
		File: ".github/workflows/ci.yml",
		Name: "CI runs stable OCR model smoke",
		Needles: []string{
			"OCR Model Smoke",
			"Build OCR model packages",
			"-model all",
			"Build OCR worker for smoke",
			"Run stable OCR model package smoke",
			"--smoke",
			"--runtime-dir \"${APP_DIR}/tools/onnxruntime/linux-amd64\"",
			"--model-dir \"release-out/ocr-model-smoke/ppocrv5-mobile-zh-en\"",
			"--must-contain RecordingFreedom",
			"--must-contain 文字识别",
		},
	},
	{
		File: ".github/workflows/ci.yml",
		Name: "CI runs PIP export pixel smoke",
		Needles: []string{
			"Prepare Linux FFmpeg tools for PIP export smoke",
			"Run PIP export pixel smoke",
			"./cmd/pip-export-smoke -synthetic -width 640 -height 360 -duration 1s",
			"./bin/pip-export-smoke${ext}",
			"-synthetic -width 640 -height 360 -duration 1s",
		},
	},
	{
		File: ".github/workflows/ci.yml",
		Name: "CI builds all desktop platforms",
		Needles: []string{
			"windows-x64",
			"windows-arm64",
			"macos-x64",
			"macos-arm64",
			"linux-x64",
			"linux-arm64",
			"windows-11-arm",
			"macos-15-intel",
			"ubuntu-24.04-arm",
			"./scripts/ensure-unix-ffmpeg.sh",
			"wails3 task darwin:package",
			"wails3 task linux:build",
			"recordingfreedom-${{ matrix.name }}",
		},
	},
	{
		File: ".github/workflows/release.yml",
		Name: "Release builds RNNoise dynamic artifacts",
		Needles: []string{
			"RNNOISE_TAG: rnnoise_dynamic",
			"Build RNNoise dynamic module",
			"./scripts/build-rnnoise-windows.ps1",
			"./scripts/build-rnnoise-unix.sh",
			"wails3 task windows:build ARCH=\"${{ matrix.arch }}\" EXTRA_TAGS=\"${tags}\"",
			"-require-rnnoise",
			"msys2/setup-msys2@v2",
			"release: true",
			"windows_msystem: MINGW64",
			"mingw-w64-x86_64-gcc",
			"windows_cc_subdir: mingw64",
			"windows_cc_exe: gcc.exe",
			"windows_msystem: CLANGARM64",
			"mingw-w64-clang-aarch64-clang",
			"windows_cc_subdir: clangarm64",
			"windows_cc_exe: clang.exe",
			"steps.msys2.outputs.msys2-location",
			"-Compiler \"$env:CC\"",
			"cgo_enabled: \"0\"",
			"rnnoise_dynamic: \"true\"",
			"RNNoise native DSP is built from source as a dynamic module for every desktop artifact",
			"including Windows ARM64",
			"tools/rnnoise.dll",
			"Contents/MacOS/tools/librnnoise.dylib",
			"tools/librnnoise.so",
		},
	},
	{
		File: ".github/workflows/release.yml",
		Name: "Release runs platform OCR worker stable smoke across desktop matrix",
		Needles: []string{
			"Build stable OCR model package for platform smoke",
			"Run platform OCR worker stable smoke",
			"./cmd/ocr-model-package -model ppocrv5-mobile-zh-en",
			"./cmd/ocr-worker-platform-smoke",
			"tools/ocr-worker/${worker_goos}-${{ matrix.arch }}/rf-ocr-worker${ext}",
			"tools/onnxruntime/${worker_goos}-${{ matrix.arch }}",
			"ocr-worker-platform-smoke.json",
			"Stable OCR model package was not produced for platform smoke.",
		},
	},
	{
		File: ".github/workflows/release.yml",
		Name: "Release gate runs frontend e2e gates",
		Needles: []string{
			"Install Playwright Chromium",
			"Run frontend e2e",
			"npm run test:e2e",
			"tee frontend-e2e.log",
			"Frontend e2e failed",
			"Clean frontend e2e artifacts before Go tests",
			"rm -rf frontend/test-results frontend/playwright-report frontend/frontend-e2e.log",
			"set +e",
			"tee go-test.log",
			"set -e",
			"GITHUB_STEP_SUMMARY",
			"Go test failed",
		},
	},
	{
		File: ".github/workflows/release.yml",
		Name: "Release notes distinguish whiteboard preview from overlay acceptance",
		Needles: []string{
			"Whiteboard / Excalidraw board and recording annotation",
			"opens the normal whiteboard",
			"opens the annotation overlay",
			"Whiteboard scene persistence and export",
			"Recording annotation package flow",
			"Completed cross-platform annotation overlay acceptance",
			"real Windows/macOS/Linux evidence is still required",
			"transparent click-through",
			"multi-monitor/high-DPI geometry",
			"real hand-drawn annotation packages",
		},
	},
	{
		File: ".github/workflows/release.yml",
		Name: "Release notes include smart screenshot and whiteboard history behavior",
		Needles: []string{
			"focused-window screenshot",
			"Smart screenshot and region assist",
			"RegionSmartCandidate",
			"mg-chao/snow-shot",
			"manual normal whiteboard save now writes the Excalidraw scene and a PNG snapshot into screenshot history",
			"mode=whiteboard",
			"recording annotation saves continue to write into the active .rfrec annotation package",
		},
	},
	{
		File: ".github/workflows/release.yml",
		Name: "Release stages verified Windows portable zip and installer",
		Needles: []string{
			"./scripts/ensure-windows-ffmpeg.ps1 -Architecture \"${{ matrix.ffmpeg_arch }}\"",
			"Install Windows installer tooling",
			"Build Windows installer",
			"ARG_WAILS_${{ matrix.nsis_arch }}_BINARY",
			"setup.exe",
			"tools/ffmpeg.exe",
			"tools/ffprobe.exe",
			"tools/rnnoise.dll",
			"tools/THIRD_PARTY_FFMPEG.txt",
			"tools/THIRD_PARTY_NOTICES.txt",
			"tools/desktop-doctor.exe",
			"tools/video-smoke.exe",
			"tools/audio-smoke.exe",
			"tools/pip-export-smoke.exe",
			"tools/annotation-export-smoke.exe",
			"tools/annotation-overlay-evidence-check.exe",
			"tools/ocr-desktop-evidence-export.exe",
			"tools/ocr-desktop-evidence-check.exe",
			"tools/ocr-desktop-evidence-plan.exe",
			"tools/ocr-desktop-evidence-session.exe",
			"tools/ocr-translation-smoke.exe",
			"tools/ocr-secret-store-smoke.exe",
			"tools/ocr-worker/windows-${{ matrix.arch }}/rf-ocr-worker.exe",
			"tools/run-windows-portable-smoke.ps1",
			"./scripts/verify-windows-portable.ps1",
			"Stable OCR model package was not produced for Windows portable verification.",
			"-OcrModelPackagePath",
			"./scripts/verify-windows-installer.ps1",
		},
	},
	{
		File: ".github/workflows/release.yml",
		Name: "Release stages full desktop platform artifacts",
		Needles: []string{
			"windows-x64",
			"windows-arm64",
			"macos-x64",
			"macos-arm64",
			"linux-x64",
			"linux-arm64",
			"windows-11-arm",
			"macos-15-intel",
			"ubuntu-24.04-arm",
			"./scripts/ensure-unix-ffmpeg.sh",
			"wails3 task darwin:package",
			"wails3 task linux:build",
			"RecordingFreedom-${{ matrix.name }}-${{ github.ref_name }}-app.zip",
			"RecordingFreedom-${{ matrix.name }}-${{ github.ref_name }}-portable.tar.gz",
			"./scripts/verify-macos-app-zip.sh",
			"./scripts/verify-linux-portable.sh",
			"Stable OCR model package was not produced for macOS app verification.",
			"Stable OCR model package was not produced for Linux portable verification.",
			"Full desktop build matrix is enabled for Windows x64/arm64, macOS x64/arm64, and Linux x64/arm64",
			"macOS app bundles include Contents/MacOS/recordingfreedom",
			"Contents/MacOS/tools/ocr-desktop-evidence-export",
			"Contents/MacOS/tools/ocr-desktop-evidence-check",
			"Contents/MacOS/tools/ocr-desktop-evidence-plan",
			"Contents/MacOS/tools/ocr-desktop-evidence-session",
			"Contents/MacOS/tools/ocr-translation-smoke",
			"Contents/MacOS/tools/ocr-secret-store-smoke",
			"tools/ocr-worker/darwin-${{ matrix.arch }}/rf-ocr-worker",
			"Contents/MacOS/tools/librnnoise.dylib",
			"Linux portable archives include recordingfreedom",
			"tools/ocr-desktop-evidence-export",
			"tools/ocr-desktop-evidence-check",
			"tools/ocr-desktop-evidence-plan",
			"tools/ocr-desktop-evidence-session",
			"tools/ocr-translation-smoke",
			"tools/ocr-secret-store-smoke",
			"tools/ocr-worker/linux-${{ matrix.arch }}/rf-ocr-worker",
			"tools/librnnoise.so",
		},
	},
	{
		File: ".github/workflows/release.yml",
		Name: "Release stages OCR worker in desktop artifacts",
		Needles: []string{
			"Build OCR worker",
			"tools/ocr-worker/${worker_goos}-${{ matrix.arch }}",
			"CGO_ENABLED=0 GOOS=\"${worker_goos}\" GOARCH=\"${{ matrix.arch }}\" go build",
			"tools/ocr-worker/windows-${{ matrix.arch }}/rf-ocr-worker.exe",
			"tools/ocr-worker/darwin-${{ matrix.arch }}/rf-ocr-worker",
			"tools/ocr-worker/linux-${{ matrix.arch }}/rf-ocr-worker",
			"-Architecture \"${{ matrix.ffmpeg_arch }}\"",
			"OCR protocol worker is built for every desktop architecture",
			"Native ONNX OCR inference, stable model smoke, and release-catalog package metadata are release-gated",
		},
	},
	{
		File: ".github/workflows/release.yml",
		Name: "Release stages ONNX Runtime for OCR preflight",
		Needles: []string{
			"Prepare Windows ONNX Runtime",
			"./scripts/ensure-windows-onnxruntime.ps1 -Architecture \"${{ matrix.ffmpeg_arch }}\"",
			"Prepare Unix ONNX Runtime",
			"./scripts/ensure-unix-onnxruntime.sh --platform \"${{ matrix.platform }}\" --arch \"${{ matrix.ffmpeg_arch }}\"",
			"tools/onnxruntime/windows-${{ matrix.arch }}",
			"tools/onnxruntime/linux-${{ matrix.arch }}",
			"ONNX Runtime v1.23.2 CPU runtime is bundled under tools/onnxruntime/<os-arch>/",
			"worker --capabilities --runtime-dir",
		},
	},
	{
		File: ".github/workflows/release.yml",
		Name: "Release builds stable OCR model package artifact",
		Needles: []string{
			"Build OCR Model Package",
			"Build OCR model packages",
			"go run ./cmd/ocr-model-package",
			"-model all",
			"-catalog-output ../release-out/ocr-models/ocr-model-catalog.json",
			"-release-base-url \"https://github.com/lemon-casino/RecordingFreedom/releases/download/${{ github.ref_name }}\"",
			"Run stable OCR model package smoke",
			"--smoke",
			"--must-contain RecordingFreedom",
			"--must-contain 文字识别",
			"Verify stable OCR model package artifact",
			"ppocrv5-mobile-zh-en/manifest.json",
			"ppocrv5-mobile-zh-en/det.onnx",
			"ppocrv5-mobile-zh-en/cls.onnx",
			"ppocrv5-mobile-zh-en/rec.onnx",
			"ppocrv5-mobile-zh-en/keys.txt",
			"ppocrv5-mobile-zh-en/smoke.png",
			"ppocrv5-mobile-zh-en/smoke.expected.json",
			"ocr-model-catalog.json",
			"SHA256SUMS-ocr-models.txt",
			"RecordingFreedom-ocr-models",
			"needs: [build, model-package]",
		},
	},
	{
		File: ".github/workflows/release.yml",
		Name: "Release verifies published downloads after upload",
		Needles: []string{
			"Verify published release downloads",
			"./scripts/verify-release-artifacts.ps1",
			"-Repository \"${GITHUB_REPOSITORY}\"",
			"-TagName \"${TAG_NAME}\"",
			"-Targets all",
			"-Architectures x64,arm64",
			"release-download-verification",
			"Upload release download verification evidence",
			"RecordingFreedom-release-download-verification",
			"release-artifact-verification.json",
		},
	},
	{
		File: ".github/workflows/release.yml",
		Name: "Release upload is filtered, complete, and retried",
		Needles: []string{
			`*/ocr-secret-store-smoke/*|*/ocr-worker-platform-smoke/*`,
			`RecordingFreedom-*|SHA256SUMS-*.txt|ocr-model-catalog.json|ppocr*.zip`,
			"Duplicate release asset basename",
			"RecordingFreedom-windows-x64-${TAG_NAME}-portable.zip",
			"RecordingFreedom-windows-arm64-${TAG_NAME}-portable.zip",
			"Required release assets are missing before upload",
			"upload_asset()",
			"attempt ${attempt}/3",
			`gh release upload "${TAG_NAME}" "${asset}" --clobber`,
			"Release upload finished but these assets are missing from ${TAG_NAME}",
			`gh api "repos/${GITHUB_REPOSITORY}/releases/tags/${TAG_NAME}" --jq '.assets[].name'`,
			`comm -23 "${expected_asset_names}" "${actual_asset_names}"`,
		},
	},
	{
		File: "scripts/build-rnnoise-windows.ps1",
		Name: "Windows RNNoise dynamic module builder emits x64 and arm64 DLLs",
		Needles: []string{
			`ValidateSet("x64", "arm64")`,
			"likely_voice_enhancer.c",
			"rnnoise.dll",
			"LIKELY_VOICE_ENHANCER_BUILD_DLL",
			"Resolve-CompilerPath",
			`C:\msys64\mingw64\bin\gcc.exe`,
			`C:\msys64\clangarm64\bin\clang.exe`,
			"Resolved RNNoise compiler",
			"Assert-PEMachine",
			"0x8664",
			"0xAA64",
		},
	},
	{
		File: "scripts/build-rnnoise-unix.sh",
		Name: "Unix RNNoise dynamic module builder emits dylib and so modules",
		Needles: []string{
			"--platform linux|macos",
			"likely_voice_enhancer.c",
			"librnnoise.dylib",
			"librnnoise.so",
			"LIKELY_VOICE_ENHANCER_BUILD_DLL",
			"Mach-O.*arm64",
			"ELF 64-bit",
		},
	},
	{
		File: "scripts/ensure-windows-ffmpeg.ps1",
		Name: "Windows FFmpeg bundler selects x64 and arm64 tools",
		Needles: []string{
			`ValidateSet("x64", "arm64")`,
			"ffmpeg-master-latest-win64-gpl.zip",
			"ffmpeg-master-latest-winarm64-gpl.zip",
			"Architecture:",
			"THIRD_PARTY_FFMPEG.txt",
		},
	},
	{
		File: "scripts/ensure-unix-ffmpeg.sh",
		Name: "Unix FFmpeg bundler pins checksummed macOS and Linux tools",
		Needles: []string{
			"n8.1.2-1",
			"ffmpeg-osx-x64",
			"ffprobe-osx-x64",
			"ffmpeg-osx-arm64",
			"ffprobe-osx-arm64",
			"ffmpeg-linux-x64",
			"ffprobe-linux-x64",
			"ffmpeg-linux-arm64",
			"ffprobe-linux-arm64",
			"SHA256 mismatch",
			"THIRD_PARTY_FFMPEG.txt",
		},
	},
	{
		File: "scripts/ensure-windows-onnxruntime.ps1",
		Name: "Windows ONNX Runtime bundler pins checksummed x64 and arm64 runtime",
		Needles: []string{
			`ValidateSet("x64", "arm64")`,
			"third_party\\onnxruntime\\manifest.json",
			"windows-$goArch",
			"archiveSha256",
			"archiveBytes",
			"target.libraryFiles",
			"THIRD_PARTY_ONNXRUNTIME.txt",
		},
	},
	{
		File: "scripts/ensure-unix-onnxruntime.sh",
		Name: "Unix ONNX Runtime bundler pins checksummed macOS and Linux runtime",
		Needles: []string{
			"--platform",
			"third_party/onnxruntime/manifest.json",
			"target_key=\"${goos}-${goarch}\"",
			"archiveSha256",
			"archiveBytes",
			"target[\"libraryFiles\"]",
			"THIRD_PARTY_ONNXRUNTIME.txt",
		},
	},
	{
		File: "third_party/onnxruntime/manifest.json",
		Name: "ONNX Runtime manifest covers every desktop OCR target",
		Needles: []string{
			`"version": "1.23.2"`,
			`"windows-amd64"`,
			`"windows-arm64"`,
			`"darwin-amd64"`,
			`"darwin-arm64"`,
			`"linux-amd64"`,
			`"linux-arm64"`,
			`"onnxruntime-win-x64-1.23.2.zip"`,
			`"onnxruntime-osx-x86_64-1.23.2.tgz"`,
			`"onnxruntime-linux-aarch64-1.23.2.tgz"`,
			`"archiveSha256"`,
			`"requiredLibrary"`,
		},
	},
	{
		File: "third_party/ocr-models/manifest.json",
		Name: "Stable OCR model package manifest pins PP-OCRv5 files",
		Needles: []string{
			`"ppocrv5-mobile-zh-en"`,
			`"channel": "stable"`,
			`"engine": "onnxruntime"`,
			`jingsongliu/onnxocr_model`,
			`Apache-2.0`,
			`"cls.onnx"`,
			`"det.onnx"`,
			`"rec.onnx"`,
			`"keys.txt"`,
			`"smoke.png"`,
			`"smoke.expected.json"`,
			`"sha256"`,
		},
	},
	{
		File: "third_party/ocr-models/manifest.json",
		Name: "PP-OCRv6 candidate manifests stay blocked from release packaging",
		Needles: []string{
			`"ppocrv6-mobile-zh-en"`,
			`"ppocrv6-medium-zh-en"`,
			`"releaseStatus": "candidate"`,
			`"textlineOrientation"`,
			`"mode": "none"`,
			`https://huggingface.co/PaddlePaddle/PP-OCRv6_small_det_onnx/resolve/main/inference.onnx`,
			`https://huggingface.co/PaddlePaddle/PP-OCRv6_small_rec_onnx/resolve/main/inference.yml`,
			`https://huggingface.co/PaddlePaddle/PP-OCRv6_medium_det_onnx/resolve/main/inference.onnx`,
			`https://huggingface.co/PaddlePaddle/PP-OCRv6_medium_rec_onnx/resolve/main/inference.yml`,
			`"paddleocr-character-dict-keys"`,
			`"sourceBytes"`,
			`"sourceSha256"`,
			`"b5f2bfe2bdd9448429e3e82b51c789775d9b42f2403d082b00662eb77e401c5d"`,
		},
	},
	{
		File: "app/cmd/ocr-model-package/main.go",
		Name: "OCR model package builder creates verified importable zip",
		Needles: []string{
			"ppocrv5-mobile-zh-en",
			"third_party",
			"ocr-models",
			"downloadAndVerifyFile",
			"selectedModelIDs",
			"packageModel",
			"buildPackageManifest",
			"createModelZip",
			"writeDownloadCatalog",
			"downloadCatalog",
			"-catalog-output",
			"-release-base-url",
			"TextlineOrientation",
			"RequiredModelFileNames",
			"paddleocr-character-dict-keys",
			"generatePaddleOCRCharacterDictKeys",
			"SourceBytes",
			"SourceSHA256",
			"character_dict",
			"ReleaseStatus",
			"modelReleaseStatusCandidate",
			"modelIsReleaseReady",
			"include-candidates",
			"AllowCandidate",
			"-include-candidates cannot be used with -catalog-output",
			"cannot be packaged for release",
			"Smoke.Expected",
			"SHA256:",
		},
	},
	{
		File: "app/cmd/ocr-model-source-audit/main.go",
		Name: "PP-OCRv6 source audit keeps latest quality blockers explicit",
		Needles: []string{
			"ppocrv6-mobile-zh-en",
			"ppocrv6-medium-zh-en",
			"PaddlePaddle/PP-OCRv6_small_det_onnx",
			"PaddlePaddle/PP-OCRv6_small_rec_onnx",
			"PaddlePaddle/PP-OCRv6_medium_det_onnx",
			"PaddlePaddle/PP-OCRv6_medium_rec_onnx",
			"ppocrv6-source-audit.json",
			"hash-files",
			"hashRemoteFile",
			"FileHashes",
			"GeneratedKeys",
			"paddleocr-character-dict-keys",
			"sha256.New",
			"character_dict",
			"RecCharacterCount",
			"ExpectedRecClasses",
			"cls.onnx",
			"keys.txt",
			"worker smoke",
			"ReadyForManifest",
		},
	},
	{
		File: "scripts/verify-macos-app-zip.sh",
		Name: "macOS release verifier checks app bundle contents",
		Needles: []string{
			"RecordingFreedom.app",
			"Contents/MacOS/recordingfreedom",
			"Contents/MacOS/tools",
			"CFBundleExecutable",
			"ffmpeg",
			"ffprobe",
			"ocr-desktop-evidence-export",
			"ocr-desktop-evidence-check",
			"ocr-desktop-evidence-plan",
			"ocr-desktop-evidence-session",
			"ocr-translation-smoke",
			"ocr-secret-store-smoke",
			"ocr-worker/darwin-${expected_goarch}/rf-ocr-worker",
			"--capabilities",
			"--runtime-dir",
			"onnxruntime/darwin-${expected_goarch}",
			"libonnxruntime.dylib",
			"runtimeAvailable",
			"resolve_ocr_model_dir",
			"run_ocr_stable_smoke",
			"--smoke",
			"--must-contain RecordingFreedom",
			"--must-contain 文字识别",
			"OCR worker stable model smoke verified",
			"librnnoise.dylib",
			"THIRD_PARTY_NOTICES.txt",
			"expected_arch",
			"x86_64",
			"arm64",
		},
	},
	{
		File: "scripts/verify-linux-portable.sh",
		Name: "Linux release verifier checks portable archive contents",
		Needles: []string{
			"RecordingFreedom-linux-*",
			"recordingfreedom",
			"tools/ffmpeg",
			"tools/ffprobe",
			"tools/pip-export-smoke",
			"tools/ocr-desktop-evidence-export",
			"tools/ocr-desktop-evidence-check",
			"tools/ocr-desktop-evidence-plan",
			"tools/ocr-desktop-evidence-session",
			"tools/ocr-translation-smoke",
			"tools/ocr-secret-store-smoke",
			"ocr-worker/linux-${expected_goarch}/rf-ocr-worker",
			"--capabilities",
			"--runtime-dir",
			"onnxruntime/linux-${expected_goarch}",
			"libonnxruntime.so",
			"runtimeAvailable",
			"resolve_ocr_model_dir",
			"run_ocr_stable_smoke",
			"--smoke",
			"--must-contain RecordingFreedom",
			"--must-contain 文字识别",
			"OCR worker stable model smoke verified",
			"Skipping OCR stable model smoke for Linux",
			"tools/librnnoise.so",
			"recordingfreedom.desktop",
			"THIRD_PARTY_NOTICES.txt",
			"ELF 64-bit",
			"expected_arch",
			"ARM aarch64",
		},
	},
	{
		File: "app/build/windows/nsis/project.nsi",
		Name: "Windows installer includes bundled FFmpeg tools",
		Needles: []string{
			"ARG_RECORDINGFREEDOM_TOOLS_DIR",
			`$INSTDIR\tools`,
			"ffmpeg.exe",
			"ffprobe.exe",
			"rnnoise.dll",
			"File /r",
			"ocr-worker",
			"onnxruntime",
			"THIRD_PARTY_FFMPEG.txt",
			"THIRD_PARTY_NOTICES.txt",
		},
	},
	{
		File: "scripts/verify-windows-installer.ps1",
		Name: "Windows installer verifies installed FFmpeg layout",
		Needles: []string{
			"RecordingFreedom.exe",
			"recordingfreedom.exe",
			"tools",
			"ffmpeg.exe",
			"ffprobe.exe",
			"rnnoise.dll",
			`ocr-worker\windows-$goArch\rf-ocr-worker.exe`,
			`onnxruntime\windows-$goArch`,
			"onnxruntime.dll",
			"--capabilities",
			"--runtime-dir",
			"runtimeAvailable",
			"THIRD_PARTY_FFMPEG.txt",
			"THIRD_PARTY_NOTICES.txt",
			"uninstall.exe",
		},
	},
	{
		File: "app/build/darwin/Taskfile.yml",
		Name: "macOS app bundle requires bundled FFmpeg tools",
		Needles: []string{
			"Contents/MacOS/tools",
			"tools/ffmpeg",
			"tools/ffprobe",
			"tools/ocr-worker/darwin-{{.ARCH | default ARCH}}",
			"tools/librnnoise.dylib",
			"THIRD_PARTY_FFMPEG.txt",
			"THIRD_PARTY_NOTICES.txt",
		},
	},
	{
		File: ".github/workflows/release.yml",
		Name: "Release builds desktop smoke tools",
		Needles: []string{
			"Build desktop smoke tools",
			"desktop-doctor${ext}",
			"video-smoke${ext}",
			"audio-smoke${ext}",
			"pip-export-smoke${ext}",
			"annotation-export-smoke${ext}",
			"annotation-overlay-evidence-check${ext}",
			"ocr-desktop-evidence-export${ext}",
			"ocr-desktop-evidence-check${ext}",
			"ocr-desktop-evidence-plan${ext}",
			"ocr-desktop-evidence-session${ext}",
			"ocr-translation-smoke${ext}",
			"ocr-secret-store-smoke${ext}",
			"rf-ocr-worker${ext}",
			"run-windows-portable-smoke.ps1",
		},
	},
	{
		File: ".github/workflows/release.yml",
		Name: "Release runs PIP export pixel smoke",
		Needles: []string{
			"Prepare Linux FFmpeg tools for PIP export smoke",
			"Run PIP export pixel smoke",
			"./cmd/pip-export-smoke -synthetic -width 640 -height 360 -duration 1s",
			"./bin/pip-export-smoke${ext}",
			"-synthetic -width 640 -height 360 -duration 1s",
			"FFmpeg PIP export verification that samples the final MP4 PIP pixels",
		},
	},
	{
		File: "app/build/windows/Taskfile.yml",
		Name: "Windows build keeps GUI subsystem",
		Needles: []string{
			`-ldflags="-w -s -H windowsgui"`,
		},
	},
	{
		File: "scripts/verify-windows-portable.ps1",
		Name: "Windows portable zip verifies architecture-specific GUI PE metadata",
		Needles: []string{
			`ValidateSet("x64", "arm64")`,
			"Assert-PEMetadata",
			"Assert-PowerShellScript",
			"Assert-FileContains",
			"ExpectedSubsystem 2",
			"0x8664",
			"0xAA64",
			"recordingfreedom.exe",
			"tools/rnnoise.dll",
			"tools/ocr-worker/windows-$goArch/rf-ocr-worker.exe",
			"tools/onnxruntime/windows-$goArch/onnxruntime.dll",
			"Can-ExecuteWindowsTarget",
			"Skipping OCR worker execution for Windows $Architecture on non-compatible host",
			"--capabilities",
			"--runtime-dir",
			"runtimeAvailable",
			"OcrModelPackagePath",
			"Resolve-OcrModelDirectory",
			"Invoke-OcrStableSmoke",
			"--smoke",
			"--must-contain RecordingFreedom",
			"--must-contain 文字识别",
			"OCR worker stable model smoke verified",
			"THIRD_PARTY_NOTICES.txt",
			"@excalidraw/excalidraw",
			"Copyright (c) 2020 Excalidraw",
			"tools/desktop-doctor.exe",
			"tools/video-smoke.exe",
			"tools/audio-smoke.exe",
			"tools/pip-export-smoke.exe",
			"tools/annotation-export-smoke.exe",
			"tools/annotation-overlay-evidence-check.exe",
			"tools/ocr-desktop-evidence-export.exe",
			"tools/ocr-desktop-evidence-check.exe",
			"tools/ocr-desktop-evidence-plan.exe",
			"tools/ocr-desktop-evidence-session.exe",
			"tools/ocr-translation-smoke.exe",
			"tools/ocr-secret-store-smoke.exe",
			"tools/run-windows-portable-smoke.ps1",
			"secret-store-smoke",
			"pip-export-pixels",
			"-synthetic",
		},
	},
	{
		File: "app/tools/THIRD_PARTY_NOTICES.txt",
		Name: "Third-party notices include RNNoise and Excalidraw licenses",
		Needles: []string{
			"RNNoise",
			"License: BSD-style license",
			"Copyright (c) 2017, Mozilla",
			"Neither the name of the Xiph.Org Foundation",
			"@excalidraw/excalidraw",
			"License: MIT",
			"Copyright (c) 2020 Excalidraw",
			`THE SOFTWARE IS PROVIDED "AS IS"`,
		},
	},
	{
		File: "scripts/run-windows-portable-smoke.ps1",
		Name: "Windows portable smoke runner executes real recording diagnostics",
		Needles: []string{
			"desktop-doctor.exe",
			"video-smoke.exe",
			"audio-smoke.exe",
			"pip-export-smoke.exe",
			"annotation-export-smoke.exe",
			"annotation-overlay-evidence-check.exe",
			"ocr-desktop-evidence-export.exe",
			"ocr-desktop-evidence-check.exe",
			"ocr-desktop-evidence-plan.exe",
			"ocr-desktop-evidence-session.exe",
			"ocr-translation-smoke.exe",
			"ocr-secret-store-smoke.exe",
			"translation-smoke",
			"secret-store-smoke",
			"pip-export-pixels",
			"-synthetic",
			"RunAnnotationLong",
			"LongAnnotationDurations",
			"LongAnnotationSegments",
			"annotation-long-snapshots",
			"annotation-long-element-pngs",
			"-segments=",
			"-timeline=element-pngs",
			"-source-type=region",
			"-source-type=window",
			"RECORDINGFREEDOM_FFMPEG_PATH",
			"-source-type=region",
			"-source-type=window",
			"-microphone",
			"-system",
			"-rnnoise",
		},
	},
	{
		File: "docs/12-annotation-overlay-platform-smoke.md",
		Name: "Annotation overlay has real platform smoke standard",
		Needles: []string{
			"录制标注 Overlay 实机验收标准",
			"annotation-export-smoke",
			"annotation-overlay-evidence-check",
			"不能替代真实桌面上的透明窗口",
			"全屏、单屏、区域、锁定窗口",
			"多屏幕",
			"高 DPI",
			"点击穿透",
			".rfrec/annotations/",
			"annotations/overlay-diagnostics.jsonl",
			"exports/recording.mp4",
			"evidence/annotation-overlay",
		},
	},
	{
		File: "app/cmd/annotation-overlay-evidence-check/main.go",
		Name: "Annotation overlay evidence checker verifies real package artifacts",
		Needles: []string{
			"-evidence-dir",
			"manifest annotations.enabled is required",
			"annotation target geometry does not match source geometry",
			"validateEvidenceREADME",
			"README.md is missing evidence records",
			"artifact source",
			"validatePlatformFile",
			"platform.txt is missing display environment records",
			"displayResolutionPattern",
			"requiredScreenshotEvidence",
			"requiredRecordingEvidence",
			"requireEvidenceNamedFiles",
			"is missing evidence files",
			"validateAppLog",
			"app-log.jsonl is missing required events",
			"recording/start-request sourceType=",
			"annotation-overlay/show targetType=",
			"recpackage.AnnotationEventsFile",
			"recpackage.AnnotationOverlayDiagnosticsFile",
			"missing %s diagnostic event",
			"1m recording package",
			"5m recording package",
			"requiredEvidenceSourceChecks",
			"source all-screens package",
			"source screen package",
			"source region package",
			"source window package",
			"requireSourceType",
			"diagnostics.sync.screen.durationMs",
			"missing drawing hit-regions event with full canvas rect",
			"missing pass-through hit-regions event without full canvas rect",
			"hitRegionsContainCanvasRect",
			"hitRegionsContainPill",
			"validateAnnotationEvents",
			"missing element-created/element-updated/element-deleted event",
			"scene-snapshot has invalid snapshotPath",
			"findAnnotationSnapshot",
			"recpackage.ProbeMP4",
			"MP4 video track is missing",
			"diagnostics.sync.screen.durationMs",
			"exportplan.DefaultOutputPath",
		},
	},
	{
		File: "docs/README.md",
		Name: "Docs index links annotation overlay smoke standard",
		Needles: []string{
			"12-annotation-overlay-platform-smoke.md",
			"真实桌面验收矩阵",
			"不能只靠 `annotation-export-smoke` 宣称完成",
		},
	},
	{
		File: "scripts/verify-windows-preview-release.ps1",
		Name: "Windows preview release asset can be downloaded and verified",
		Needles: []string{
			"api.github.com/repos",
			"SHA256SUMS-windows-x64",
			"Get-FileHash -Algorithm SHA256",
			"verify-windows-portable.ps1",
		},
	},
	{
		File: "scripts/verify-release-artifacts.ps1",
		Name: "Release artifacts can be downloaded and verified across desktop targets",
		Needles: []string{
			"RecordingFreedom-release-artifacts-verifier",
			"Waiting for release asset matching $Pattern",
			"Start-Sleep -Seconds 5",
			"$OutFile.part",
			"Retrying in ${delaySeconds}s",
			"ToArray()",
			"RecordingFreedom-windows-$arch-*-portable.zip",
			"RecordingFreedom-windows-$arch-*-setup.exe",
			"RecordingFreedom-macos-$arch-*-app.zip",
			"RecordingFreedom-linux-$arch-*-portable.tar.gz",
			"SHA256SUMS-ocr-models.txt",
			"ocr-model-catalog.json",
			"ppocrv5-mobile-zh-en-*.zip",
			"verify-windows-portable.ps1",
			"modelVerification",
			"OcrModelPackagePath",
			"macArgs",
			"linuxArgs",
			"verify-windows-installer.ps1",
			"verify-macos-app-zip.sh",
			"verify-linux-portable.sh",
			"OcrDesktopEvidenceVisualDir",
			"OcrDesktopEvidenceDataRoot",
			"OcrDesktopEvidenceToolsDir",
			"Can-ExecuteWindowsTarget",
			"Can-ExecuteMacOSTarget",
			"Can-ExecuteLinuxTarget",
			"Expand-WindowsPortableToolsDir",
			"Expand-MacOSAppToolsDir",
			"Expand-LinuxPortableToolsDir",
			"ocr-desktop-evidence-plan",
			"ocr-desktop-evidence-plan.exe",
			"ocr-desktop-evidence-session",
			"ocr-desktop-evidence-session.exe",
			"ocr-desktop-evidence-export/check/plan/session",
			"ocr-desktop-evidence-tools",
			"macos-$arch",
			"linux-$arch",
			"autoOcrDesktopEvidenceToolsDir",
			"compatible release package tools were auto-extracted",
			"Invoke-OcrDesktopEvidenceExport",
			"OCR desktop evidence DataRoot is required",
			"$dataRootPath = Resolve-FullPath $DataRoot",
			"DataRoot = $dataRootPath",
			`"--data-root", $dataRootPath`,
			"export-ocr-desktop-evidence.ps1",
			"export-ocr-desktop-evidence.sh",
			"OcrDesktopEvidenceRequested",
			"check-report.json",
			"release-artifact-verification.json",
			"RequireContentVerification",
		},
	},
}

func main() {
	var root string
	flag.StringVar(&root, "root", "", "repository root; defaults to walking up from the current directory")
	flag.Parse()

	result, err := run(root)
	if err != nil {
		_ = json.NewEncoder(os.Stdout).Encode(map[string]any{
			"ok":    false,
			"error": err.Error(),
		})
		os.Exit(1)
	}
	encoder := json.NewEncoder(os.Stdout)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(result); err != nil {
		fmt.Fprintf(os.Stderr, "encode release config report: %v\n", err)
		os.Exit(1)
	}
	if !result.OK {
		os.Exit(1)
	}
}

func run(root string) (report, error) {
	resolved, err := resolveRoot(root)
	if err != nil {
		return report{}, err
	}
	result := report{
		OK:          true,
		GeneratedAt: time.Now().UTC(),
		Root:        resolved,
		Checks:      make([]checkResult, 0, len(releaseConfigChecks)),
	}
	for _, check := range releaseConfigChecks {
		item := evaluateCheck(resolved, check)
		if item.Status != "ready" {
			result.OK = false
		}
		result.Checks = append(result.Checks, item)
	}
	return result, nil
}

func resolveRoot(root string) (string, error) {
	if strings.TrimSpace(root) != "" {
		abs, err := filepath.Abs(root)
		if err != nil {
			return "", err
		}
		return abs, nil
	}
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(wd, ".github", "workflows", "release.yml")); err == nil {
			return wd, nil
		}
		parent := filepath.Dir(wd)
		if parent == wd {
			return "", fmt.Errorf("could not find repository root from %q", wd)
		}
		wd = parent
	}
}

func evaluateCheck(root string, check configCheck) checkResult {
	path := filepath.Join(root, filepath.FromSlash(check.File))
	data, err := os.ReadFile(path)
	if err != nil {
		return checkResult{File: check.File, Name: check.Name, Status: "blocked", Message: err.Error()}
	}
	content := string(data)
	missing := make([]string, 0)
	for _, needle := range check.Needles {
		if !strings.Contains(content, needle) {
			missing = append(missing, needle)
		}
	}
	if len(missing) > 0 {
		return checkResult{
			File:    check.File,
			Name:    check.Name,
			Status:  "blocked",
			Message: "missing required release gate text: " + strings.Join(missing, " | "),
		}
	}
	return checkResult{File: check.File, Name: check.Name, Status: "ready"}
}
