// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pip$0 from "../pip/models.js";

export interface PauseSegmentPlan {
    "startOffsetMs": number;
    "endOffsetMs": number;
    "durationMs": number;
}

export interface Plan {
    "packageDir": string;
    "manifestPath": string;
    "outputPath": string;
    "screenInputPath": string;
    "webcamInputPath"?: string;
    "webcamStartOffsetMs"?: number;
    "pipPreset": string;
    "pipConfig": pip$0.Config;
    "pipRect": pip$0.Rect;
    "pipLayout": pip$0.Placement;
    "timelineBase"?: string;
    "audioDiagnosticsPath"?: string;
    "videoDiagnosticsPath"?: string;
    "pauseSegments"?: PauseSegmentPlan[] | null;
    "warnings"?: string[] | null;
}
