// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Info {
    "rootDir": string;
    "videoDir": string;
}

export interface StorageStatus {
    "rootDir": string;
    "videoDir": string;
    "writable": boolean;
    "freeSpaceKnown": boolean;
    "availableBytes": number;
    "minimumRecommendedBytes": number;
    "status": string;
    "reason"?: string;
}
